### ISSUE TITLE
Some trial and failure on supporting apollo 8.0. 

### ISSUE THREAD

**Issue by EternalSaga** [guardstrikelab/carla_apollo_bridge#103]
First of all, the official Apollo Docker only supports Python 3.6. As a result, all my effort is focused on version 0.9.13 because the latest Carla client no longer supports Python 3.6.  
I copied all the [source code](https://github.com/guardstrikelab/carla_apollo_bridge/tree/master/src) into the path “apollo/cyber/carla_bridge” and tried to build Apollo. There are some Bazel codes that need to be changed. For example, many protobuf files have been moved into “modules/common_msgs”, so the dependency path of Bazel needs to be updated. Furthermore, some configuration files need to be added as resources in Bazel.  
```bazel
py_binary(
    name = "bridge",
    srcs = ["bridge.py"],
    data = ["CARLA_VERSION",
        "config/settings.yaml",],
deps = [
        "//cyber/python/cyber_py3:cyber",
        "//cyber/python/cyber_py3:cyber_time",
        "//cyber/python/cyber_py3:parameter",
        "//cyber/proto:parameter_py_pb2",
        "//cyber/carla_bridge/carla_proto/proto:carla_proto_py",
        "//modules/data/proto:frame_py_pb2",
        "//modules/common_msgs/basic_msgs:geometry_py_pb2",
        "//modules/common_msgs/sensor_msgs:pointcloud_py_pb2",
        "//modules/common_msgs/sensor_msgs:sensor_image_py_pb2",
        "//modules/common_msgs/localization_msgs:pose_py_pb2",
        "//modules/common_msgs/localization_msgs:localization_py_pb2",
        "//modules/common_msgs/localization_msgs:gps_py_pb2",
        "//modules/common_msgs/localization_msgs:imu_py_pb2",
        "//modules/common_msgs/perception_msgs:perception_obstacle_py_pb2",
        "//modules/common_msgs/chassis_msgs:chassis_py_pb2",
        "//modules/common_msgs/control_msgs:control_cmd_py_pb2",
        "//modules/common_msgs/planning_msgs:planning_py_pb2",
        "//modules/common_msgs/routing_msgs:routing_py_pb2",
        "//modules/common_msgs/transform_msgs:transform_py_pb2",
        "//modules/common_msgs/basic_msgs:error_code_py_pb2",
        "//modules/common_msgs/sensor_msgs:gnss_best_pose_py_pb2",
        "//modules/common_msgs/sensor_msgs:heading_py_pb2",
        "//modules/common_msgs/sensor_msgs:ins_py_pb2",
        "//modules/common_msgs/sensor_msgs:imu_py_pb2",
],
```
Then just building the cyber module and try to run the bridge.
```bash
./apollo.sh build cyber
./bazel-bin/cyber/carla_bridge/carla_cyber_bridge/bridge
./bazel-bin/cyber/carla_bridge/carla_spawn_objects/carla_spawn_objects
```
During this stage, some Python type casting error need to be fixed. After a few changes, the apollo bridge could be run successfully.  

However, this bridge cannot run normally. There are a great many of errors when it communicates with apollo dreamview.

**Comment by WilliaJing** [comment]
Indeed, Carla0.9.14 does not support Python3.6, so are you using Carla0.9.13+Apollo8.0? What kind of error do you have?

**Comment by EternalSaga** [comment]
> Indeed, Carla0.9.14 does not support Python3.6, so are you using Carla0.9.13+Apollo8.0? What kind of error do you have?

Yes, I am using CARLA 0.9.13 and Apollo 8.0 on my Windows PC. I encountered some errors, listed below:

1. Initially, the car model in Dreamview was perpendicular to the lane. To fix this issue, I tried changing [line](https://github.com/guardstrikelab/carla_apollo_bridge/blob/2ffb46bd369ea7b508fd6dc1c248ba3720db30d9/src/carla_common/transforms.py#L122) to the following code:
```cpp
yaw = -math.radians(carla_rotation.yaw+90)
```
This seems to have worked, but the **point cloud orientation rotates 90 degrees**.

2. When I tried sending a routine from Dreamview to the CARLA server, I noticed that if I didn't click the sim control button, both the car in Dreamview and the one in Carla wouldn't move. However, when I clicked it, the car in Dreamview would teleport between two positions and the CARLA car would make strange movements. 
3. The camera view couldn't show on Dreamview.

**Comment by EternalSaga** [comment]
> Indeed, Carla0.9.14 does not support Python3.6, so are you using Carla0.9.13+Apollo8.0? What kind of error do you have?

I followed the main tutorial on the homepage to set up my environment, but I encountered some unexpected issues.   
Firstly, the route editing function in Dreamview proved to be unhelpful.   
Secondly, as illustrated in the attached screenshot, the point cloud appears orthotropic to the car's orientation.
<img width="1273" alt="Screenshot 2023-05-25 160720" src="https://github.com/guardstrikelab/carla_apollo_bridge/assets/15174504/af9fad71-7d69-4fe9-9635-860b78778dfb">

**Comment by WilliaJing** [comment]
Do you choose two points, you can only choose one point，
Do you use Windows?We only test in Ubuntu environment

**Comment by EternalSaga** [comment]
> 

Sorry, I'm not sure what you mean by 'Two points'. Although I used Edge browser and captured the screenshot on Windows, my actual working environment is Linux.

**Comment by WilliaJing** [comment]
> the route editing function in Dreamview

the route editing function only to choose one point in Dreamview.
If the car still cannot move, you can try starting these steps over again.
did you succeed in apollo7.0?

**Comment by EternalSaga** [comment]
> > the route editing function in Dreamview
> 
> the route editing function only to choose one point in Dreamview. If the car still cannot move, you can try starting these steps over again. did you succeed in apollo7.0?

@WilliaJing Thank you for your suggestion. I was finally successful, but there are still many bugs in carla-apollo-bridge. For example, I cannot send the routine to CARLA twice and I must restart all processes. Additionally, as I mentioned earlier, the point cloud in Dreamview appears to be rotated 90 degrees along the Y-axis.

**Comment by WilliaJing** [comment]
@EternalSaga yes,as you said, we are improving it and you can always pull requests to us with new features.
Additionally, new issues can be raised again, and you can close this issue.

**Comment by Michael-Fuu** [comment]
> > > the route editing function in Dreamview
> > 
> > 
> > the route editing function only to choose one point in Dreamview. If the car still cannot move, you can try starting these steps over again. did you succeed in apollo7.0?
> 
> @WilliaJing Thank you for your suggestion. I was finally successful, but there are still many bugs in carla-apollo-bridge. For example, I cannot send the routine to CARLA twice and I must restart all processes. Additionally, as I mentioned earlier, the point cloud in Dreamview appears to be rotated 90 degrees along the Y-axis.

It is that mean you put carla-bridge source codes into apollo source codes and compile them together? I'm not sure if I understand it correctly, but in that case, you only need the Apollo container and the simulation container?
