### ISSUE TITLE
Dreamview页面中画出的Point Cloud与carla中激光雷达点云整体存在90度差异

### ISSUE THREAD

**Issue by GimpelZhang** [guardstrikelab/carla_apollo_bridge#104]
## Describe the bug
辛苦，辛苦！

我在使用中发现，Dreamview中打开Layer Menu/Perception/Point Cloud选项后，页面中画出的点云和carla实际送入Apollo算法的点云似乎存在90度的整体差异，如下图所示：

<img width="1280" alt="bridge_img1" src="https://github.com/guardstrikelab/carla_apollo_bridge/assets/17154358/910ecc12-eecb-474b-8498-4c93c20465fe">

绿色圆圈中显然是前方车辆的点云，但是通过绿色3d bbox可知算法已经给出了车辆在前方的感知结果。

如果我在objects.json文件中，将ego_vehicle的lidar的yaw角设成-90，则点云整体旋转了90，dreamview页面中画出的点云能够和实际情况对应，但是感知结果的3d bbox又向左旋转了90度，如下图所示：

![bridge_img2](https://github.com/guardstrikelab/carla_apollo_bridge/assets/17154358/154f2066-7508-42f5-8ab8-3926ddb8b5ee)

### In what area(s)?

 /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

**Comment by meua** [comment]
Try to modify the following content  in `src/carla_cyber_bridge/lidar.py`, you can see if it meets your expectations.
```python
        lidar_data[:, 1] *= -1

#        idar_data = lidar_data[:, :3]
#        lidar_data[:, 0:2] *= -1
#        # we also need to permute x and y
#        lidar_data = lidar_data[..., [1, 0, 2]]
```
![image](https://github.com/guardstrikelab/carla_apollo_bridge/assets/11570442/d3da3888-c786-4a9c-861a-7f3edbc9d6f9)

**Comment by PhilWallace** [comment]
> Try to modify the following content in `src/carla_cyber_bridge/lidar.py`, you can see if it meets your expectations.
> 
> ```python
>         lidar_data[:, 1] *= -1
> 
> #        idar_data = lidar_data[:, :3]
> #        lidar_data[:, 0:2] *= -1
> #        # we also need to permute x and y
> #        lidar_data = lidar_data[..., [1, 0, 2]]
> ```
> 
> ![image](https://user-images.githubusercontent.com/11570442/242179327-d3da3888-c786-4a9c-861a-7f3edbc9d6f9.png)

Thanks. This code works for me.

**Comment by WilliaJing** [comment]
I verified it, and I did solve my problem.

**Comment by rodhw** [comment]
What was the transformation that worked for you?

**Comment by GimpelZhang** [comment]
> What was the transformation that worked for you?

Actually the solution in the comments in this issue didn't work for me. But I didn't work on it after all.
