### ISSUE TITLE
carla map to apollo

### ISSUE THREAD

**Issue by fpeanut** [guardstrikelab/carla_apollo_bridge#106]
你好，请问carlatown01是怎么导入到apollo内的，我想将其他地图也导入到apollo内

**Comment by SEEKERXC** [comment]
See [Release 0.3.0](https://github.com/guardstrikelab/carla_apollo_bridge/releases/tag/0.3.0)
Problem solved by [Release 0.3.0](https://github.com/guardstrikelab/carla_apollo_bridge/releases/tag/0.3.0), so this issue is closed.
