### ISSUE TITLE
can't spawn object

### ISSUE THREAD

**Issue by phamhieutn44** [guardstrikelab/carla_apollo_bridge#109]
I build carla docker brigde follow to the introduction
But when I run "python carla_spawn_objects/carla_spawn_objects.py", the code don't do anything and show:
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0606 12:12:59.510480  6437 cyber_time_wrap.cc:338] [] init _cyber_time
I0606 12:12:59.515213  6437 cyber_timer_wrap.cc:164] [] init _cyber_timer
I0606 12:12:59.520190  6437 cyber_parameter_wrap.cc:639] [] init _cyber_parameter
I0606 12:12:59.525905  6437 global_data.cc:119] [spawn_objects] host ip: 10.20.14.207
[2023-06-06 12:13:04,532] [carla_bridge] [WARNING]: Shutting down.
[2023-06-06 12:13:04,532] [carla_bridge] [INFO]: Destroying spawned objects...

I check the code of .py file, seem it can't run from line 73: response = self.call_service(self.spawn_object_service, spawn_object_request)
Maybe "call_service" function have wrong but I dont know how to fix it.
Can you help me?

**Comment by WilliaJing** [comment]
Did you not start bridge.py successfully ?The carla_spawn_objects.py can only be executed after the bridge is started.

**Comment by phamhieutn44** [comment]
yeah i think i have same problem with #49. When I check all of modules, I found that when I run apollo dreamview, and check **cyber_node list** across to introductions in [Deploy Network](https://github.com/guardstrikelab/carla_apollo_bridge/blob/master/docs/deployment_introduction.md), I seen none node have been activate. What should I do? 
![image](https://github.com/guardstrikelab/carla_apollo_bridge/assets/83834932/5c712efd-1d43-4859-963e-3d7fee3a0109)

**Comment by WilliaJing** [comment]
@phamhieutn44 Have you run the following code?
```
./apollo.sh build_gpu
