### ISSUE TITLE
关于添加apollo添加新的carla地图方案

### ISSUE THREAD

**Issue by fpeanut** [guardstrikelab/carla_apollo_bridge#113]
我在这位博主下找到了添加新地图的方案，并测试可行。
链接：https://github.com/MaisJamal/Carla_apollo_maps

**Comment by Minphie** [comment]
请问这个里面每个图都测试可行吗？我试了加载town04地图dreamviewer会崩

**Comment by Minphie** [comment]
> 我在这位博主下找到了添加新地图的方案，并测试可行。 链接：https://github.com/MaisJamal/Carla_apollo_maps

请问这个里面每个图都测试可行吗？我试了加载town04地图dreamviewer会崩

**Comment by fpeanut** [comment]
> 

town确实会崩，你用5或者3 也能满足你的要求。另外，你们apollo8的carla也能用，能分享下项目吗

**Comment by SEEKERXC** [comment]
我们最近正在攻克地图难题，在imap( https://github.com/daohu527/imap )的基础上修复了停止线以及地图坐标，后续应该会把结果开源，更新到这里

**Comment by SEEKERXC** [comment]
See [Release 0.3.0](https://github.com/guardstrikelab/carla_apollo_bridge/releases/tag/0.3.0)
Problem solved by [Release 0.3.0](https://github.com/guardstrikelab/carla_apollo_bridge/releases/tag/0.3.0), so this issue is closed.
