### ISSUE TITLE
Carla-Apollo on g4dn

### ISSUE THREAD

**Issue by Abdurrahman-Elhefnawy** [guardstrikelab/carla_apollo_bridge#122]
I am trying to use AWS VM to run Carla simulator, is the g4dn xlarge machine good enough to run the simulator smoothly?

g4dn xlarge spec :
vCPUs | 4
Memory (GiB) | 16.0
Memory per vCPU (GiB) | 4.0
Physical Processor | Intel Xeon Family
Clock Speed (GHz) | 2.5
CPU Architecture | x86_64
GPU | 1
GPU Architecture | nvidia t4 tensor core
Video Memory (GiB) | 16
GPU Compute Capability (?) | 7.5
FPGA | 0

**Comment by SEEKERXC** [comment]
Such a configuration is definitely not enough, mainly because the CPU and memory are too small. It is recommended to choose at least 2xlarge.

**Comment by SEEKERXC** [comment]
Problem solved, so close
