### ISSUE TITLE
apollo没有反应

### ISSUE THREAD

**Issue by caixxuan** [guardstrikelab/carla_apollo_bridge#131]
按照教程运行起来终端没有报错，carla有反应，车不动。但是apollo似乎没有反应，没有连接上bridge，请问是什么原因呢

![2023-08-18 16-19-09 的屏幕截图](https://github.com/guardstrikelab/carla_apollo_bridge/assets/110223255/672f411a-be28-4760-8df9-1529cedb8e80)

![2023-08-18 16-19-36 的屏幕截图](https://github.com/guardstrikelab/carla_apollo_bridge/assets/110223255/37dbff45-ba58-4bcc-bd56-4fbdc2791226)

**Comment by caixxuan** [comment]
我已经解决了该问题，方法是将carla的host和apollo中的setup.sh的cyber_IP设置为相同地址，参考172.18.0.1

**Comment by charles-lei** [comment]
Kindly reminder the code repository has been updated with clearer architecture. Welcome to have a try.
