### ISSUE TITLE
nvcc fatal   : Unsupported gpu architecture 'computes_75'

### ISSUE THREAD

**Issue by caixxuan** [guardstrikelab/carla_apollo_bridge#137]
**Note:** If you have a general support question and are looking for a quicker response, please checkout our discord channel for answers from the community:
https://bbs.carla.org.cn/ask

## In what area(s)?

> /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Ask your question here
when i process to ./apollo.sh build_gpu, i encounter the error:
nvcc fatal   : Unsupported gpu architecture 'computes_89';
after i search for this issue, i try to change to compute_75 or any other, but it cannot work, my nvidia is RTX4080 laptop

**Comment by SEEKERXC** [comment]
We have consulted the Apollo development team, and they clearly stated that **Apollo 8.0 does not support the 4080 graphics card architecture**

**Comment by caixxuan** [comment]
> We have consulted the Apollo development team, and they clearly stated that **Apollo 8.0 does not support the 4080 graphics card architecture**

thanks a lot! so I'd like to ask two more questions:
1. my computer with 4080 does not support any all apollo? such as the tag0.2 or 0.1 cannot work too?;
2. 3050 Ti laptop is ok working with the newest tag0.3 with apollo8.0?

**Comment by SEEKERXC** [comment]
> > We have consulted the Apollo development team, and they clearly stated that **Apollo 8.0 does not support the 4080 graphics card architecture**
> 
> thanks a lot! so I'd like to ask two more questions:
> 
> 1. my computer with 4080 does not support any all apollo? such as the tag0.2 or 0.1 cannot work too?;
> 2. 3050 Ti laptop is ok working with the newest tag0.3 with apollo8.0?

1. Yes, because neither Apollo7.0 nor Apollo8.0 support 4080 graphics card.
2. 3050 Ti should be supported with the newest tag0.3

**Comment by caixxuan** [comment]
thank you very much

**Comment by SEEKERXC** [comment]
Problem solved, issue closed

**Comment by SmallChester** [comment]
@XiaoFei9704  I wonder if the bridge could support apollo v9.0.0alpha, because I only have 4080!  Thank you for your reply!
