### ISSUE TITLE
ModuleNotFoundError when running python main.py

### ISSUE THREAD

**Issue by LCaptainJackSparrow** [guardstrikelab/carla_apollo_bridge#145]
What should be done to resolve the following errors after running main.py inside the Apollo container. 
Carla has already been run。
![2023-08-31 12-03-30屏幕截图](https://github.com/guardstrikelab/carla_apollo_bridge/assets/101320438/19472884-8f53-4b15-94d6-b749385a2fbe)
![Uploading 2023-08-31 12-03-45屏幕截图.png…]()

**Comment by Abdurrahman-Elhefnawy** [comment]
how did you solved this problem?

**Comment by hlyyy** [comment]
> how did you solve this problem?

hi, do you solve this problem now?

**Comment by hlyyy** [comment]
> > how did you solve this problem?
> 
> hi, do you solve this problem now?

I solve this problem by running ```source /apollo/cyber/setup.bash``` in apollo docker
