### ISSUE TITLE
Failed to start Dreamview

### ISSUE THREAD

**Issue by LCaptainJackSparrow** [guardstrikelab/carla_apollo_bridge#146]
Open dreamview normally for the first time. After re-entering the container, dreamview cannot be started. I have tried building a GPU or restarting my computer, but it has not worked. The log file is as follows. Is there any solution?
![2023-08-31 15-14-52屏幕截图](https://github.com/guardstrikelab/carla_apollo_bridge/assets/101320438/41066583-15ff-4bb4-94a5-bd103c620197)
[nohup.txt](https://github.com/guardstrikelab/carla_apollo_bridge/files/12483487/nohup.txt)

**Comment by 2019211753** [comment]
I can solve it only by deleting all the images and containers and download them again

**Comment by LCaptainJackSparrow** [comment]
I did the same thing. But after opening the dreamview and setting the route, the vehicle cannot move in both dreamview and carla. Do you know how to solve it？

**Comment by 2019211753** [comment]
> I did the same thing. But after opening the dreamview and setting the route, the vehicle cannot move in both dreamview and carla. Do you know how to solve it？

I'm the same with you. Looking forward to the new updates of the repository.

**Comment by SEEKERXC** [comment]
Sorry, this is due to a problem with our latest carla_town05 map. You can delete carla_town05 in modules/map/data first

**Comment by LCaptainJackSparrow** [comment]
Thank you very much for your reply.
After deleting carla_town05 in modules/map/data, I can open dreamview. However, it was found  that the localization module could not be opened in the module controller. In addition, after adding point of interest in the route editing, the route path cannot be generated.I think this is because the localization module cannot be opened. How should this situation be resolved?
![Uploading 2023-09-06 16-23-42屏幕截图.png…]()

**Comment by SEEKERXC** [comment]
Our latest master should have fixed the problem you encountered, you can pull it down and try
