### ISSUE TITLE
How to stop the python main.py in apollo docker?

### ISSUE THREAD

**Issue by LCaptainJackSparrow** [guardstrikelab/carla_apollo_bridge#148]
I tried Ctrl+C, but it didn't work. At present, I can only directly shut down the terminal and then re-enter the Docker to resolve the issue.

**Comment by SEEKERXC** [comment]
Because an infinite loop is used in the program, ctrl+c cannot exit, and we will fix this problem later. 
You can use ctrl+z to exit, if there is an exception after exiting, you can kill the process

**Comment by LCaptainJackSparrow** [comment]
Thank you very much for your reply
