### ISSUE TITLE
the Localization module could not be opened in the module controller.

### ISSUE THREAD

**Issue by LCaptainJackSparrow** [guardstrikelab/carla_apollo_bridge#153]
After deleting carla_town05 in modules/map/data, I can open dreamview. However, it was found that the localization module could not be opened in the module controller. In addition, after adding point of interest in the route editing, the route path cannot be generated.I think this is because the localization module cannot be opened. How should this situation be resolved?

![2023-09-06 16-23-42屏幕截图](https://github.com/guardstrikelab/carla_apollo_bridge/assets/101320438/3555ae5a-48c4-4b8f-b966-e98b3aa15b6f)

**Comment by Kitty9701** [comment]
I can not open localization module too. Can you tell me how you solved it?

**Comment by AtongWang** [comment]
I alse face this question too. How to fix it?
