### ISSUE TITLE
Reflectance map folder is invalid! and Localization Status Is Missing

### ISSUE THREAD

**Issue by wqklihbf** [guardstrikelab/carla_apollo_bridge#178]
**Note:** If you have a general support question and are looking for a quicker response, please checkout our discord channel for answers from the community:
https://bbs.carla.org.cn/ask

## In what area(s)?

> /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Ask your question here
When I was using [carla_apollo_bridge](https://githubfast.com/guardstrikelab/carla_apollo_bridge), the localization module failed to start.
When I used the command `cyber_launch start module/localization/launch/msf_localization.launch`, I encountered an error: `Reflectance map folder is invalid!`.
After changing msf to rtk, the localization module was able to start, but the Dreamview interface showed a warning: `Current Localization Status Is Missing`
![image](https://github.com/guardstrikelab/carla_apollo_bridge/assets/128605713/a4c63e22-4a57-4f96-82bd-f5b5bf00a70b)
![image](https://github.com/guardstrikelab/carla_apollo_bridge/assets/128605713/86490436-8744-4c53-ae58-0e30dd3e76a3)
![image](https://github.com/guardstrikelab/carla_apollo_bridge/assets/128605713/5381e85e-5ffa-450e-b102-76fc97b9108c)

**Comment by TayYim** [comment]
Try use RTK instead of MSF, run:
`mainboard -d /apollo/modules/localization/dag/dag_streaming_rtk_localization.dag`
to enable localization

**Comment by wqklihbf** [comment]
Thank you for your reply.
I've changed the `key:Localization's dag_files` in `/apollo/modules/dreamview/conf/hmi_modes/mkz_standard_debug.pb.txt` to `dag_streaming_rtk_localization.dag`, the Localization module is now running, but it shows `WARN` on Dreamview, I want to know how to make it `OK`.

**Comment by AOOOOOA** [comment]
> `key:Localization's dag_files` in `/apollo/modules/dreamview/conf/hmi_modes/mkz_standard_debug.pb.txt` to `dag_streaming_rtk_localization.dag`

Hi I met the same problem, how do you fix it?
