### ISSUE TITLE
IMU message buffer is empty

### ISSUE THREAD

**Issue by wqklihbf** [guardstrikelab/carla_apollo_bridge#182]
**Note:** If you have a general support question and are looking for a quicker response, please checkout our discord channel for answers from the community:
https://bbs.carla.org.cn/ask

## In what area(s)?

> /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Ask your question here
当我在Dreamview界面中启动Localization模块时，Localization显示WARN，日志里显示如下：
Log file created at: 2024/03/05 15:43:36
Running on machine: in-dev-docker
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0305 15:43:36.022807 13020 class_loader_utility.h:79] registerclass:RTKLocalizationComponent,apollo::cyber::ComponentBase,/apollo/bazel-bin/modules/localization/rtk/librtk_localization_component.so
I0305 15:43:36.043301 13020 rtk_localization_component.cc:47] Rtk localization config: localization_topic: "/apollo/localization/pose"
imu_topic: "/apollo/sensor/gnss/corrected_imu"
gps_topic: "/apollo/sensor/gnss/odometry"
broadcast_tf_frame_id: "world"
broadcast_tf_child_frame_id: "localization"
imu_list_max_size: 20
gps_imu_time_diff_threshold: 0.02
map_offset_x: 0
map_offset_y: 0
map_offset_z: 0
localization_status_topic: "/apollo/localization/msf_status"
gps_status_topic: "/apollo/sensor/gnss/ins_stat"
broadcast_tf_use_system_clock: false
E0305 15:43:37.456712 13026 rtk_localization.cc:60] IMU message buffer is empty.
E0305 15:43:37.510016 13031 rtk_localization.cc:388] Cannot find Matching IMU. IMU messages too old. Newest timestamp[1.70962e+09], GPS timestamp[1.70962e+09]
E0305 15:43:37.573695 13035 rtk_localization.cc:388] Cannot find Matching IMU. IMU messages too old. Newest timestamp[1.70962e+09], GPS timestamp[1.70962e+09]
E0305 15:43:37.637892 13023 rtk_localization.cc:388] Cannot find Matching IMU. IMU messages too old. Newest timestamp[1.70962e+09], GPS timestamp[1.70962e+09]

**Comment by rodrigoqueiroz** [comment]
Seems to be a performance issue. The Localization has a small threshold to match IMU and GPS messages. 
You can configure this value to accept larger difference, but a good localization requires good performance and up to date IMU measurement. 
  double gps_imu_time_diff_threshold_ = 0.02;
