### ISSUE TITLE
perception and traffic light module error

### ISSUE THREAD

**Issue by YangXianqi** [guardstrikelab/carla_apollo_bridge#207]
**Note:** If you have a general support question and are looking for a quicker response, please checkout our discord channel for answers from the community:
https://bbs.carla.org.cn/ask

## In what area(s)?

> /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Ask your question here
when i start the traffic light module and transform module, the traffic light module will be core dumped. the log in traffic light is:
![image](https://github.com/user-attachments/assets/e7f093a4-b28e-45e8-af55-c02fbb445878)

the transform log is:
![image](https://github.com/user-attachments/assets/4ef8aafe-69fc-4782-84cf-c9796359603a)

**Comment by JasonBourne1998** [comment]
I also meet this question, seems that in apollo8.0, the traffic light module works normally but need transfer the result into apollo. And in apollo7.0, the  traffic light module didn't work

**Comment by YangXianqi** [comment]
> I also meet this question, seems that in apollo8.0, the traffic light module works normally but need transfer the result into apollo. And in apollo7.0, the traffic light module didn't work

thanks a lot！ In apollo8.0, the trafficlight module will report the error:
```
[[1;34m/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt[0m] [1;34m [m[0;31mE1009 09:35:22.601780 736240 trafficlights_perception_component.cc:704] [perception]Can not find transform. 1728437722.575453043 frame_id: world child_frame_id: novatel Error info: Lookup would require extrapolation into the future.  Requested time 1728437722575452928 but the latest data is at time 1728437722574592000, when looking up transform from frame [novatel] to frame [world]:timeout[0m
[[1;34m/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt[0m] [1;34m [m[0;31mE1009 09:35:22.601823 736240 trafficlights_perception_component.cc:670] [perception]get pose from tf failed, child_frame_id: novatel[0m
```

Have you met this problem?

**Comment by JasonBourne1998** [comment]
> > I also meet this question, seems that in apollo8.0, the traffic light module works normally but need transfer the result into apollo. And in apollo7.0, the traffic light module didn't work
> 
> thanks a lot！ In apollo8.0, the trafficlight module will report the error:
> 
> ```
> [�[1;34m/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt�[0m] �[1;34m �[m�[0;31mE1009 09:35:22.601780 736240 trafficlights_perception_component.cc:704] [perception]Can not find transform. 1728437722.575453043 frame_id: world child_frame_id: novatel Error info: Lookup would require extrapolation into the future.  Requested time 1728437722575452928 but the latest data is at time 1728437722574592000, when looking up transform from frame [novatel] to frame [world]:timeout�[0m
> [�[1;34m/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt�[0m] �[1;34m �[m�[0;31mE1009 09:35:22.601823 736240 trafficlights_perception_component.cc:670] [perception]get pose from tf failed, child_frame_id: novatel�[0m
> ```
> 
> Have you met this problem?

你好我直接用中文吧，我这里也不是很确定，但我感觉是perception在处理的时候遇到了时间同步问题。Apollo系统尝试查找novatel和world之间的坐标变换，但请求的时间戳（1728437722575452928）比当前数据中已有的最新时间戳（1728437722574592000）要大，导致查找失败。

**Comment by YangXianqi** [comment]
> > > I also meet this question, seems that in apollo8.0, the traffic light module works normally but need transfer the result into apollo. And in apollo7.0, the traffic light module didn't work
> > 
> > 
> > thanks a lot！ In apollo8.0, the trafficlight module will report the error:
> > ```
> > [�[1;34m/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt�[0m] �[1;34m �[m�[0;31mE1009 09:35:22.601780 736240 trafficlights_perception_component.cc:704] [perception]Can not find transform. 1728437722.575453043 frame_id: world child_frame_id: novatel Error info: Lookup would require extrapolation into the future.  Requested time 1728437722575452928 but the latest data is at time 1728437722574592000, when looking up transform from frame [novatel] to frame [world]:timeout�[0m
> > [�[1;34m/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt�[0m] �[1;34m �[m�[0;31mE1009 09:35:22.601823 736240 trafficlights_perception_component.cc:670] [perception]get pose from tf failed, child_frame_id: novatel�[0m
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Have you met this problem?
> 
> 你好我直接用中文吧，我这里也不是很确定，但我感觉是perception在处理的时候遇到了时间同步问题。Apollo系统尝试查找novatel和world之间的坐标变换，但请求的时间戳（1728437722575452928）比当前数据中已有的最新时间戳（1728437722574592000）要大，导致查找失败。

是否能够加您的联系方式？您是否有对桥的代码进行修改？

**Comment by YangXianqi** [comment]
> > > I also meet this question, seems that in apollo8.0, the traffic light module works normally but need transfer the result into apollo. And in apollo7.0, the traffic light module didn't work
> > 
> > 
> > thanks a lot！ In apollo8.0, the trafficlight module will report the error:
> > ```
> > [�[1;34m/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt�[0m] �[1;34m �[m�[0;31mE1009 09:35:22.601780 736240 trafficlights_perception_component.cc:704] [perception]Can not find transform. 1728437722.575453043 frame_id: world child_frame_id: novatel Error info: Lookup would require extrapolation into the future.  Requested time 1728437722575452928 but the latest data is at time 1728437722574592000, when looking up transform from frame [novatel] to frame [world]:timeout�[0m
> > [�[1;34m/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt�[0m] �[1;34m �[m�[0;31mE1009 09:35:22.601823 736240 trafficlights_perception_component.cc:670] [perception]get pose from tf failed, child_frame_id: novatel�[0m
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Have you met this problem?
> 
> 你好我直接用中文吧，我这里也不是很确定，但我感觉是perception在处理的时候遇到了时间同步问题。Apollo系统尝试查找novatel和world之间的坐标变换，但请求的时间戳（1728437722575452928）比当前数据中已有的最新时间戳（1728437722574592000）要大，导致查找失败。

另外，我在apollo8.0上运行traffic和perception，在transform模块运行的情况下会核心段崩溃，您有遇到过吗？
![image](https://github.com/user-attachments/assets/2e761a7f-24e8-4746-bb67-b8bb4eba275b)

**Comment by YangXianqi** [comment]
> > > > I also meet this question, seems that in apollo8.0, the traffic light module works normally but need transfer the result into apollo. And in apollo7.0, the traffic light module didn't work
> > > 
> > > 
> > > thanks a lot！ In apollo8.0, the trafficlight module will report the error:
> > > ```
> > > [�[1;34m/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt�[0m] �[1;34m �[m�[0;31mE1009 09:35:22.601780 736240 trafficlights_perception_component.cc:704] [perception]Can not find transform. 1728437722.575453043 frame_id: world child_frame_id: novatel Error info: Lookup would require extrapolation into the future.  Requested time 1728437722575452928 but the latest data is at time 1728437722574592000, when looking up transform from frame [novatel] to frame [world]:timeout�[0m
> > > [�[1;34m/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt�[0m] �[1;34m �[m�[0;31mE1009 09:35:22.601823 736240 trafficlights_perception_component.cc:670] [perception]get pose from tf failed, child_frame_id: novatel�[0m
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Have you met this problem?
> > 
> > 
> > 你好我直接用中文吧，我这里也不是很确定，但我感觉是perception在处理的时候遇到了时间同步问题。Apollo系统尝试查找novatel和world之间的坐标变换，但请求的时间戳（1728437722575452928）比当前数据中已有的最新时间戳（1728437722574592000）要大，导致查找失败。
> 
> 是否能够加您的联系方式？您是否有对桥的代码进行修改？

@JasonBourne1998 你好，能帮忙看一下嘛？

**Comment by persistisok** [comment]
请问你解决这个问题了吗

**Comment by persistisok** [comment]
请问你解决这个问题了吗 @JasonBourne1998 @YangXianqi
