### ISSUE TITLE
Apollo6.0 With dreamview not work

### ISSUE THREAD

**Issue by JasonBourne1998** [guardstrikelab/carla_apollo_bridge#29]
My apollo version is 6.0 (Actually I don't know why even if I have cloned the newest Apollo version, the ./dev_start.sh would direct to 6.0).   And when I build the apollo and enter the dreamview, the page says the lidar and GPS are not activated. Interestingly, this error is missing in the official apollo.
![image](https://user-images.githubusercontent.com/51346614/206438058-16def00f-8966-4869-bc2b-7853897d8595.png)

**Comment by wohu1104** [comment]
We recommend using the following steps to see if the system can be restored.
1. Go to the apollo directory and run `./docker/scripts/dev_start.sh` 
2. Run 'bash docker/scripts/ dev_int.sh' to access the container
3. Delete the compilation cache and recompile by executing './ Apolo.sh clean -a '  and then  './ apolo.sh build_gpu ' 

Looking forward to your feedback. It is also recommended to upgrade to apollo7.0.

**Comment by JasonBourne1998** [comment]
> @JasonBourne1998 We recommend using the following steps to see if the system can be restored.
> 
> 1. Go to the apollo directory and run `./docker/scripts/dev_start.sh`
> 2. Run 'bash docker/scripts/ dev_int.sh' to access the container
> 3. Delete the compilation cache and recompile by executing './ Apolo.sh clean -a '  and then  './ apolo.sh build_gpu '
> 
> Looking forward to your feedback. It is also recommended to upgrade to apollo7.0.

Actually, I am confused about how to upgrade to 7.0. Since I already clone your apollo package at https://github.com/guardstrikelab/apollo, it ought to be 7.0.

**Comment by JasonBourne1998** [comment]
> @JasonBourne1998 We recommend using the following steps to see if the system can be restored.
> 
> 1. Go to the apollo directory and run `./docker/scripts/dev_start.sh`
> 2. Run 'bash docker/scripts/ dev_int.sh' to access the container
> 3. Delete the compilation cache and recompile by executing './ Apolo.sh clean -a '  and then  './ apolo.sh build_gpu '
> 
> Looking forward to your feedback. It is also recommended to upgrade to apollo7.0.

I have recompiled and it still does not work. I guess the error was caused by the mismatch version between dreamview(7.0) and Apollo(6.0). @daohu527 sorry to bother you, but could you plz explain why my apollo version couldn't switch to 7.0?

**Comment by yuxip** [comment]
Hi guys, sorry about the delay from our support team. Almost all of our team members got hit by covid during the past two weeks. We expect to resume our work this week, and will get back to you all soon.

**Comment by yuxip** [comment]
Hi @JasonBourne1998, 

Just because the Apollo Development Docker was tagged with "-20210914_1336" doesn't mean you're running Apollo-6.0. It is just a development environment. `dev_start.sh` will mount $APOLLO_ROOT_DIR (which is the apollo code repo you cloned from us, with version > 7.0) as /apollo within the container.

If you follow our instructions in the readme you will get an Apollo vehicle running in Carla.

Could you let us know what you're trying to achieve?

**Comment by charles-lei** [comment]
This issue will be closed if there are no more activity, thanks for your attention.

**Comment by charles-lei** [comment]
It looks like this issue hasn’t been active in longer than a few weeks. In the absence of more information, we will close it, If you find that this is still a problem, please feel free to reopen it.
