### ISSUE TITLE
apollo 7.0 routing has something wrong

### ISSUE THREAD

**Issue by Cyrus-k** [guardstrikelab/carla_apollo_bridge#30]
hello, I followed your guide and finished building carla_apollo bridge. But when i did as your Usage part said, and click setup to start cosimulation. the car won't move neither in the dreamview nor in the carla simulator. Sometimes, when i select some points in dreamview and send routing request, the red apollo routing line is even not correct. It looks like it has some mistakes with the point i chose in dreamview.
 
![Screenshot 2022-12-09 at 16-41-57 Dreamview](https://user-images.githubusercontent.com/55689315/206662097-2c8b88c6-67d1-407c-a817-04cb5565fac3.png)

**Comment by JasonBourne1998** [comment]
@Cyrus-k Hi, can you provide a screenshot of the module controller when you setup the system?

**Comment by Cyrus-k** [comment]
Hello,when I set up the system, the module controller screenshot is in the attachment.






不落樱
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "guardstrikelab/carla_apollo_bridge"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月10日(星期六) 下午3:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [guardstrikelab/carla_apollo_bridge] apollo 7.0 routing has something wrong (Issue #30)





 
@Cyrus-k Hi, can you provide a screenshot of the module controller when you setup the system?

**Comment by JasonBourne1998** [comment]
> 

Sorry, I can't see the picture.

**Comment by Cyrus-k** [comment]
Hello, when I set up the system, the picture of the module controller is as follow.
![1212_1](https://user-images.githubusercontent.com/55689315/206955016-4651d00d-9dc9-4eb6-8319-8e3287b284f6.jpg)

**Comment by Cyrus-k** [comment]
Thank you, developers. When I all reset up the system, I can use the bridge correctly. But I still want to ask if I can set many points in Route Editing module. It seems that when you click more than two or three points in the Route Editing module, the red routing line may be wrong.

**Comment by 2177361170** [comment]
@Cyrus-k @JasonBourne1998 Hello, sir, I also encountered the problem you encountered during the operation, but I did not solve the problem after resetting the system. The vehicle also cannot move. Do you have any other solutions? thank.

**Comment by yuxip** [comment]
Hi guys, sorry about the delay from our support team. Almost all of our team members got hit by covid during the past two weeks. We expect to resume our work this week, and will get back to you all soon.

**Comment by SmallChester** [comment]
> @Cyrus-k @JasonBourne1998 Hello, sir, I also encountered the problem you encountered during the operation, but I did not solve the problem after resetting the system. The vehicle also cannot move. Do you have any other solutions?The message that Dreamview prompts is Raw IMU Message Delay. IMU message is 167111046059 cycle 1.67111e+09 sec behind current time. I hope to get your advice.Thank.

I have the same question.

**Comment by AOOOOOA** [comment]
> > @Cyrus-k @JasonBourne1998楼主您好，我在操作过程中也遇到了您遇到的问题，但是重置系统后问题也没有解决，车子也是动不了，您还有其他解决办法吗？Dreamview提示的信息是Raw IMU Message Delay. IMU message is 167111046059 cycle 1.67111e+09 sec behind current time，希望得到您的指点，谢谢。
> 
> 我也有同样的问题。

same error
