### ISSUE TITLE
How to run the traffic light perception module in apollo?

### ISSUE THREAD

**Issue by 181860153** [guardstrikelab/carla_apollo_bridge#32]
Hello delevopers, I followed your guide and ran the bridge successfully. However, the traffic light perception module seemed to not be working. Therefore, the ego vehicle stopped at any crossing with a traffic light, even when the light was green. Could you tell me how to enable traffic light perception? Thank you very much!

**Comment by yuxip** [comment]
Hello sam, sorry about the delay in response. Almost all of our team members got hit by covid during the past two weeks. We expect to resume our work this week, and will get back to you soon.

**Comment by noorzzz** [comment]
Hi,

I also notice the same issue here. However, I notice that Town01's HDMap may not contain signal information (e.g. stop sign, traffic lights) in it. I think it's documented in [this part of the documentation](https://carla.readthedocs.io/en/latest/core_actors/#traffic-signs-and-traffic-lights) , and is also the case for previous carla-apollo integration attempt (https://github.com/AuroAi/carla_apollo_bridge). I'm very unfamiliar with Apollo, these two things maybe related somehow.
