### ISSUE TITLE
Sensor modules deactivate themselves

### ISSUE THREAD

**Issue by MarioAlmelaUMH** [guardstrikelab/carla_apollo_bridge#42]
Hello, I have followed the installation guide and the bridge builds and runs properly, however, I can't activate some of the modules, specifically the sensor modules (Camera, Radar, Lidar, GPS, etc.). Showing Carla sensor information in Dreamview works correctly, like showing the camera feed or the pointcloud layer. However the corresponding modules themselves are off and deactivate if I try to activate them.

![Captura de pantalla de 2023-01-13 13-43-44](https://user-images.githubusercontent.com/119304913/212325310-581aa76c-5213-4779-a90f-9bbce8b885d5.png)

In the picture above, I can't activate any of the deactivated modules, but the car still moves and drives the right way. The only major problem here is the GPS not being found.

Is this a bug, or these modules are Apollo exclusive and overwritten by Carla sensors?

Thank you in advance.

**Comment by charles-lei** [comment]
@mice2018 Do you have some knowledge about this?
