### ISSUE TITLE
How to use existing Carla Python API?

### ISSUE THREAD

**Issue by GiantSeaweed** [guardstrikelab/carla_apollo_bridge#44]
Hello developers,

Huge thanks for the efforts! I followed your doc and can successfully run the co-simulation.

Currently the Readme is about using Dreamview to config a task, send routing request, etc. I was wondering whether we users can leverage the existing Carla Python API to communicate with carla simulator and take apollo program as an agent. 

If so, we can write python code to do automatic interaction and configuration, rather than manually clicking on Dreamview webpage.

Thanks!

**Comment by yuting-fu** [comment]
I'm curious if the team plan to develop an Apollo CARLA Leaderboard agent 😃

**Comment by noorzzz** [comment]
Hi,

I don't know whether this will help or not, but I remember LGSVL (another simulator that is currently deprecated) used to provide functionality to communicate with Dreamview using Python API (i.e. turning off/on modules, setting destination). I haven't taken a look at the API in details, but it seems that it uses web sockets. I have plans to reuse that code for Apollo + CARLA, but don't rely on me :)

**Comment by newwj** [comment]
I guess you want to know how to control the Apollo module with Python.What I know is that interacting with Apollo can only be written through some channels provided by Cyberrt. You can modify these MESSAGE writing channels. 
The official documentation is as follows:
[Apollo document](https://apollo.baidu.com/community/Apollo-Homepage-Document/Apollo_Doc_CN_6_0)

**Comment by WilliaJing** [comment]
It looks like this issue hasn’t been active in longer than a few weeks. In the absence of more information, we will close it, If you find that this is still a problem, please feel free to reopen it.

**Comment by AOOOOOA** [comment]
> this issue hasn’t been active in longer than a few weeks. In the absence of more information, we will close it, If you find that this is still a problem, please feel free to reopen it.

Hi, I am also curious about this question. Do you have plans to perfect the documentation of Carla_Apollo_Bridge? For now, it is hard for developers to quickly start using it. For example, the content in the link you provided is hard to understand and apply, and there is a lack of explanations about where it should be inserted.
