### ISSUE TITLE
Compose file invalid

### ISSUE THREAD

**Issue by justindachille** [guardstrikelab/carla_apollo_bridge#45]
Hi,

I was following setup instructions, and on this line:
`cd carla_apollo_bridge/scripts
./docker_run_carla.sh`

I am getting the following error: 
<img width="685" alt="Screen Shot 2023-01-23 at 2 25 27 PM" src="https://user-images.githubusercontent.com/5369523/214164933-d05d0f3c-02d8-4581-b692-c8f288f23c34.png">
Option is set to nvidia by default:
<img width="655" alt="Screen Shot 2023-01-23 at 2 33 14 PM" src="https://user-images.githubusercontent.com/5369523/214165204-7e9771d9-cb87-41a8-9a43-373ccda28e39.png">

**Comment by Yandong-Luo** [comment]
I have the same issue

**Comment by charles-lei** [comment]
Try to keep your docker compose version consistent with your local box @justindachille

**Comment by justindachille** [comment]
Thanks everyone! I was able to run it with modifying the version to '2.4', as @Yandong-Luo suggested, as well as running his command of `sudo chown $USER /var/run/docker.sock`

I had to modify the command to `sudo chown [user]:[group] /var/run/docker.sock`, where group was `docker`.
