### ISSUE TITLE
No module named '_cyber_wrapper'

### ISSUE THREAD

**Issue by starrye** [guardstrikelab/carla_apollo_bridge#48]
`>>> from cyber_py3 import cyber, cyber_time, cyber_timer, parameter`

Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/apollo/cyber/python/cyber_py3/cyber.py", line 39, in <module>
           _CYBER = importlib.import_module('_cyber_wrapper')
       File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_cyber_wrapper'

**Comment by charles-lei** [comment]
Could you provide some more detailed information about which step causes this problem？

**Comment by starrye** [comment]
> Could you provide some more detailed information about which step causes this problem？

sorry, I've already handled this problem by  running `source cyber/setup.bash`
