### ISSUE TITLE
Python Can't Connect

### ISSUE THREAD

**Issue by justindachille** [guardstrikelab/carla_apollo_bridge#49]
Hi,

I am following the quickstart guide. When I run 
`cd /apollo/cyber/carla_bridge`
`python carla_cyber_bridge/bridge.py`
I get this result:
`I0205 06:55:27.050416  6706 global_data.cc:119] [cyber_py] host ip: 172.17.0.2
[2023-02-05 06:55:27,052] [carla_bridge] [INFO]: The config file path is carla_cyber_bridge/config/settings.yaml.
[2023-02-05 06:55:27,055] [carla_bridge] [INFO]: Trying to connect to 172.17.0.2:8888
[2023-02-05 06:56:27,065] [carla_bridge] [ERROR]: Error: time-out of 60000ms while waiting for the simulator, make sure the simulator is ready and connected to 172.17.0.2:8888
`

I also tried with 0.1, but the issue is when I grep the IP address of the carla docker container it says: `            "SecondaryIPAddresses": null,
            "IPAddress": "172.17.0.2",
                    "IPAMConfig": null,
                    "IPAddress": "172.17.0.2",
`. 

This is why I tried running the config with both 0.1 and 0.2, however neither connected. 
However, I can only connect to Apollo on 172.17.0.1:8888, not 172.17.0.2:8888, even when I rebuild with CYBER_IP=172.17.0.2 in `apollo/cyber/setup.bash`

Is there a way to change the carla docker IP to use 0.1? That is the only thing I can think of but I don't know how to try.

**Comment by justindachille** [comment]
Ok, I undid some changes and reran it. The issue is that it still doesn't connect: even with apollo dreamview running on the same port: 
<img width="1540" alt="image" src="https://user-images.githubusercontent.com/5369523/217969184-aadfb6e3-d49b-4fc5-8ef6-28e7cc194f74.png">

I also tried it on the default port of 2000: 
<img width="776" alt="image" src="https://user-images.githubusercontent.com/5369523/217969249-28e2d372-4825-486c-a6c7-bdf7c3a9d91d.png">

I can access apollo on this ip and port in the browser just fine: 
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/5369523/217969344-66357537-5659-4156-84ec-76c2a79bd835.png">

**Comment by justindachille** [comment]
I also upped the timeout to 600 seconds to see if it would connect in a longer period of time, to no avail.

**Comment by charles-lei** [comment]
Is Carla running on your localbox? The carla_bridge will connect to Carla at 172.17.0.1:2000 by default.

> I also upped the timeout to 600 seconds to see if it would connect in a longer period of time, to no avail.

**Comment by charles-lei** [comment]
> I also upped the timeout to 600 seconds to see if it would connect in a longer period of time, to no avail.

Try this to run Carla:
```
cd carla_apollo_bridge/scripts
./docker_run_carla.sh
```

**Comment by justindachille** [comment]
Yes, I am running carla and apollo all on the same machine.

> cd carla_apollo_bridge/scripts
> ./docker_run_carla.sh

The output of this command runs fine: 
<img width="327" alt="image" src="https://user-images.githubusercontent.com/5369523/218290364-95f86022-00f4-43a1-b06c-d288ff24182c.png">
I can see the UE environment after it runs: 
<img width="1371" alt="image" src="https://user-images.githubusercontent.com/5369523/218290376-1558fdba-a37f-4657-a612-b109d5f4546c.png">
The issue occurrs when I am running the command to connect to apollo: 

`cd /apollo/cyber/carla_bridge`
`python carla_cyber_bridge/bridge.py`

**Comment by guardstrikeo** [comment]
> Yes, I am running carla and apollo all on the same machine.
> 
> > cd carla_apollo_bridge/scripts
> > ./docker_run_carla.sh
> 
> The output of this command runs fine: <img alt="image" width="327" src="https://user-images.githubusercontent.com/5369523/218290364-95f86022-00f4-43a1-b06c-d288ff24182c.png"> I can see the UE environment after it runs: <img alt="image" width="1371" src="https://user-images.githubusercontent.com/5369523/218290376-1558fdba-a37f-4657-a612-b109d5f4546c.png"> The issue occurrs when I am running the command to connect to apollo:
> 
> `cd /apollo/cyber/carla_bridge` `python carla_cyber_bridge/bridge.py`

Is there a 'docker0' network of bridge type on your machine? 
![image](https://user-images.githubusercontent.com/80501478/218291089-d4c36891-7aec-4b7a-ad22-c46e759117c3.png)

**Comment by justindachille** [comment]
<img width="661" alt="image" src="https://user-images.githubusercontent.com/5369523/218293909-b9922af0-6323-4f25-83ce-eba0cd0e5b5e.png">
Yes, I see the same result.

**Comment by guardstrikeo** [comment]
I'm not sure if you are running in a special network environment or if you have modified some configuration files. Actually,  carla_ apollo_bridge container can be connected to Carla through docker0: 172.17.0.1:2000. Apollo and dreamview is running on your host with host network, so you can access dreamview from your host through 172.17.0.1:8888 or localhost: 8888. Here are also some explanations: https://github.com/AuroAi/carla_apollo_bridge ，hope it helps.

**Comment by guardstrikeo** [comment]
I'm not sure if you are running in a special network environment or if you have modified some configuration files. Actually, carla_ apollo_bridge container can connect to Carla through docker0: 172.17.0.1:2000. Apollo and dreamview is running on your host with host network, so you can access dreamview from your host through 172.17.0.1:8888 or localhost: 8888. Here are also some explanations: https://github.com/AuroAi/carla_apollo_bridge ，hope it helps.

**Comment by justindachille** [comment]
I had modified settings.yaml to use port 8888, but that didn't work, so I changed it back to port 2000, and it still doesn't connect: 
<img width="800" alt="image" src="https://user-images.githubusercontent.com/5369523/218936428-77222939-0fa4-41be-883f-382849b87009.png">
Neither works if I modify settings to use 0.2 port: 
<img width="786" alt="image" src="https://user-images.githubusercontent.com/5369523/218938489-fcca2bf3-7816-46f5-93bf-73aa93430611.png">

**Comment by justindachille** [comment]
Have you given up on this issue?

**Comment by charles-lei** [comment]
Hi @justindachille,  sorry for the untimely reply because we are using non-working hours to maintain this codebase.

You can try this to test if you can connect Carla with IP 172.17.0.1:2000
1. make sure your Carla is running:
```
./docker_run_carla.sh
```
2. create a dockerfile using below code
```shell
FROM carlasim/carla:0.9.13
USER root
RUN rm /etc/apt/sources.list.d/*
RUN apt-get update  -y
RUN apt-get install -y libjpeg-dev libtiff5-dev
```
3. build test images

`docker build -t carla:test .`

4. run test. Your Carla will be connected and have a dynamic weather.
```shell
docker run -it --rm --privileged --gpus all -u root -e DISPLAY=$DISPLAY -e PYTHONPATH=/home/carla/PythonAPI/carla/dist/carla-0.9.13-py3.7-linux-x86_64.egg -v /tmp/.X11-unix:/tmp/.X11-unix:rw  carla:test python3 /home/carla/PythonAPI/examples/dynamic_weather.py --host 172.17.0.1
```

**Comment by justindachille** [comment]
No problem, I wasn't aware of the situation. Thank you for spending the time to help me with my naive issue.

I get a timeout with running your final command. I appended the current running dockers as well. Steps 1-3 went well for me however. 
<img width="1632" alt="Screen Shot 2023-03-07 at 9 01 23 PM" src="https://user-images.githubusercontent.com/5369523/223624078-24a820bf-28e0-4d51-a291-142f22f51f03.png">

**Comment by charles-lei** [comment]
Hi @justindachille , the codebase has been updated ，try to pull the new codechanges and re-run Carla:
```
git pull
cd scripts
./docker_run_carla.sh
```
now the step 4 above will be success if everything went well.

**Comment by justin-ucdavis** [comment]
Sorry, no dice, I'm not sure what I'm doing wrong here. 

<img width="1670" alt="Screen Shot 2023-03-08 at 11 20 42 AM" src="https://user-images.githubusercontent.com/122572107/223821541-10cabc9b-e755-4d3d-945b-5bad821d8b30.png">

This is of course after running all commands in "Build and run Apollo" and doing "Run Carla" to the command `./apollo.sh build_cyber opt`, which passes, however, of course, I am unable to run the following 'bridge.py' or step 4, which is shown in the screenshot. I did just pull the recent changes as well.

**Comment by charles-lei** [comment]
Another simple test:
```
docker run --rm alpine ping 172.17.0.1
```
![image](https://user-images.githubusercontent.com/11240968/224041654-ac18745f-f08b-4897-ab06-6862497efce1.png)

If it does not work, I think there must be something wrong with your network. You have to google "ping 172.17.0.1 fails" for more info. I have no idea why you cannot ping 'docker0' in docker containers. 

Additionally, I searched some posts, maybe you can upgrade your OS and reinstall Docker to solve this problom.

**Comment by justindachille** [comment]
This command runs fine for me, weirdly enough.

<img width="627" alt="image" src="https://user-images.githubusercontent.com/5369523/225245425-7008a177-90cd-4570-9086-03f02c9e14de.png">

**Comment by Ming2888** [comment]
carla_cyber_0.9.13 seems using Apollo 5. I kept getting  "ERROR: ld.so: object 'libcaffe2_gpu.so' from LD_PRELOAD cannot be preloaded" when I run ./apollo.sh build_cyber opt. Is there any way to fix it? 

Thank you!

**Comment by Ming2888** [comment]
The bridge seems working , however in Dreamview the car does not move after I send the routing request.  Any feedback would be greatly appreciated.

**Comment by WilliaJing** [comment]
> carla_cyber_0.9.13 seems using Apollo 5. I kept getting "ERROR: ld.so: object 'libcaffe2_gpu.so' from LD_PRELOAD cannot be preloaded" when I run ./apollo.sh build_cyber opt. Is there any way to fix it?
> 
> Thank you!

Hi, @Ming2888 This problem has been solved, you can view #82 ,you can pull the code and run again.

**Comment by WilliaJing** [comment]
It looks like this issue hasn’t been active in longer than a few weeks. In the absence of more information, we will close it, If you find that this is still a problem, please feel free to reopen it.

**Comment by WilliaJing** [comment]
> 好的，我取消了一些更改并重新运行。问题是它仍然无法连接：即使 apollo dreamview 在同一端口上运行： <img alt="图像" width="1540" src="https://user-images.githubusercontent.com/5369523/217969184-aadfb6e3-d49b-4fc5-8ef6-28e7cc194f74.png">
> 
> 我还在默认端口2000上尝试过： <img alt="图像" width="776" src="https://user-images.githubusercontent.com/5369523/217969249-28e2d372-4825-486c-a6c7-bdf7c3a9d91d.png">
> 
> 我可以在浏览器中通过这个ip和端口访问apollo： <img alt="图像" width="1057" src="https://user-images.githubusercontent.com/5369523/217969344-66357537-5659-4156-84ec-76c2a79bd835.png">

@justindachille you can refer to this issue #83
