### ISSUE TITLE
ImportError: No module named carla

### ISSUE THREAD

**Issue by dajiba6** [guardstrikelab/carla_apollo_bridge#53]
Failed when running bridge.py. This issue can be fixed by typing pip install carla==0.9.13,but every time after building the container I need to install carla again. Is there any way to fix this problem permanently?

**Comment by newwj** [comment]
what's wrong when you running bridge.py ? Can you give a picture or say clearly

**Comment by charles-lei** [comment]
> 

Carla module has been installed through[ Dockerfile  ](https://github.com/guardstrikelab/carla_apollo_bridge/blob/master/docker/Dockerfile). Please keeping your codebase up to date.

**Comment by charles-lei** [comment]
This issue will be closed if there are no more activity.

**Comment by charles-lei** [comment]
It looks like this issue hasn’t been active in longer than a few weeks. In the absence of more information, we will close it, If you find that this is still a problem, please feel free to reopen it.
