### ISSUE TITLE
how to use "listen" in carla_spawn_objects to collect sensor data?

### ISSUE THREAD

**Issue by dajiba6** [guardstrikelab/carla_apollo_bridge#56]

**Comment by charles-lei** [comment]
Sensor data can be retrieved from Carla, See [Carla's document](https://carla.readthedocs.io/en/latest/core_sensors/). FYR.

**Comment by charles-lei** [comment]
@dajiba6 we will close this issue if it is inactive for a long time.

**Comment by charles-lei** [comment]
It looks like this issue hasn’t been active in longer than a few weeks. In the absence of more information, we will close it, If you find that this is still a problem, please feel free to reopen it.
