### ISSUE TITLE
FROM auroai/cyber:v5.0.0 cannot reach

### ISSUE THREAD

**Issue by zengxianming** [guardstrikelab/carla_apollo_bridge#57]
[+] Building 36.8s (3/3) FINISHED                                                                                                                                                                           
 => [internal] load build definition from Dockerfile                                                                                                                                                   0.0s
 => => transferring dockerfile: 1.08kB                                                                                                                                                                 0.0s
 => [internal] load .dockerignore                                                                                                                                                                      0.1s
 => => transferring context: 2B                                                                                                                                                                        0.0s
 => ERROR [internal] load metadata for docker.io/auroai/cyber:v5.0.0                                                                                                                                  36.7s
------
 > [internal] load metadata for docker.io/auroai/cyber:v5.0.0:
------
Dockerfile:1
--------------------
   1 | >>> FROM auroai/cyber:v5.0.0
   2 |     # cyber / bridge requirements
   3 |     RUN apt update && \
--------------------
ERROR: failed to solve: DeadlineExceeded: DeadlineExceeded: auroai/cyber:v5.0.0: failed to copy: httpReadSeeker: failed open: failed to do request: Get "https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/2a/2a3554af161b8086fc06c5b1a242eb3f3766d3211ee331e3701925170f26be73/data?verify=1677235646-Vqw5Oc0yw2zsYRsm0nkn28qg3SI%3D": dial tcp 104.18.125.25:443: i/o timeout

**Comment by charles-lei** [comment]
try to run  `docker pull auroai/cyber:v5.0.0` frist and make sure it succeed.

**Comment by zengxianming** [comment]
> 

@charles-lei I have try it. cannot pull as well. Could you please push a new docker images. Thanks :)

**Comment by charles-lei** [comment]
> > 
> 
> @charles-lei I have try it. cannot pull as well. Could you please push a new docker images. Thanks :)

Hi, this docker image is available on DockerHub: https://hub.docker.com/r/auroai/cyber, if you cannot pull,  try to configure your default docker registry. Here is an example http://mirrors.ustc.edu.cn/help/dockerhub.html

**Comment by zengxianming** [comment]
> 

thanks i soloved it!
