### ISSUE TITLE
run docker  problem

### ISSUE THREAD

**Issue by biubiubiu919** [guardstrikelab/carla_apollo_bridge#61]
when i run "./run_docker.sh", the terminator shows "access control disabled, clients can connect from any host
024c762facf2c1bf78c431c297a7d3c4275692d290fb17e6d48ff2668cda55ba"

**Comment by charles-lei** [comment]
Try to run this command in your terminal

`xhost root:local`

**Comment by biubiubiu919** [comment]
thanks a lot，the command“xhost +local:root" works
