### ISSUE TITLE
Where to get other carla maps?

### ISSUE THREAD

**Issue by dylanyd** [guardstrikelab/carla_apollo_bridge#62]
Now there is only a town01 map in Apollo. Does anyone know how to import other maps? 
Another question is that the existing town01 map doesn't have traffic light information. How to add traffic light information to the map?
Thanks for help.

**Comment by ldh2020** [comment]
You change maps from opendrive to apollo map by lgsvl.

**Comment by MingfeiCheng** [comment]
> Now there is only a town01 map in Apollo. Does anyone know how to import other maps? Another question is that the existing town01 map doesn't have traffic light information. How to add traffic light information to the map? Thanks for help.

You can save OpenDrive format maps from CARLA. Refer to save_to_disk in https://carla.readthedocs.io/en/latest/python_api/. Then you need to convert OpenDrive formt to Apollo format.

**Comment by SEEKERXC** [comment]
So far, we have done a lot of work on map conversion, and supporting the signal lights. Town01 and town02 has been completed and will be updated soon. More maps will also be updated one by one.

**Comment by SEEKERXC** [comment]
Problem solved by [Release 0.3.0](https://github.com/guardstrikelab/carla_apollo_bridge/releases/tag/0.3.0), so this issue is closed.
