### ISSUE TITLE
Problem occurs when run " python XXXX.py " in the carla_bridge container

### ISSUE THREAD

**Issue by eromreve123** [guardstrikelab/carla_apollo_bridge#63]
In the container I run this:
root@59dc9f58b601:/apollo/cyber/carla_bridge# python carla_cyber_bridge/bridge.py

Below is the error:

WARNING: Logging before InitGoogleLogging() is written to STDERR
I0304 14:33:41.795066  6354 cyber_time_wrap.cc:338] [] init _cyber_time
I0304 14:33:41.799541  6354 cyber_timer_wrap.cc:164] [] init _cyber_timer
I0304 14:33:41.804082  6354 cyber_parameter_wrap.cc:639] [] init _cyber_parameter
I0304 14:33:41.906601  6354 global_data.cc:119] [cyber_py] host ip: 172.17.0.2
[2023-03-04 14:33:41,910] [carla_bridge] [INFO]: The config file path is carla_cyber_bridge/config/settings.yaml.
[2023-03-04 14:33:41,913] [carla_bridge] [INFO]: Trying to connect to 172.17.0.1:2000
[2023-03-04 14:33:41,916] [carla_bridge] [ERROR]: Error: rpc::rpc_error during call in function version
Traceback (most recent call last):
  File "carla_cyber_bridge/bridge.py", line 485, in <module>
    main()
  File "carla_cyber_bridge/bridge.py", line 471, in main
    carla_world = carla_client.get_world()
RuntimeError: rpc::rpc_error during call in function version

**Comment by eromreve123** [comment]
I could really need some help, thank you!

**Comment by charles-lei** [comment]
Are you using Carla 0.9.13? It seems your python carla client version mismatch with Carla version. 

> I could really need some help, thank you!

**Comment by WilliaJing** [comment]
It looks like this issue hasn’t been active in longer than a few weeks. In the absence of more information, we will close it, If you find that this is still a problem, please feel free to reopen it.

**Comment by WilliaJing** [comment]
@eromreve123 
* Check whether Carla-Simulator-1 is running

If it is running,you can try to follow the steps below
1. Install firewall (if already installed, skip this step)
```
sudo apt-get install firewalld
```
2. close firewall
```
systemctl stop firewalld.service
```
3. Test whether the container carla_cyber_0.9.14 can connect to the Carla service
```
docker exec -ti carla_cyber_0.9.14 bash
curl -v 172.17.0.1:2000
```
If the following information is displayed,the firewalld was closed
>root@a5b2fce9f53f:/apollo# curl -v 172.17.0.1:2000
 Rebuilt URL to: 172.17.0.1:2000/
Trying 172.17.0.1...
TCP_NODELAY set
 Connected to 172.17.0.1 (172.17.0.1) port 2000 (#0)
 GET / HTTP/1.1
 Host: 172.17.0.1:2000
 User-Agent: curl/7.58.0
 Accept: */*

Else the following content is displayed, it indicates that the firewall has not been successfully shut down and Carla cannot perform joint simulation with Apollo normally:
>curl: (7) Failed to connect to 172.17.0.1 port 2000: No route to host

**You first need to turn off the firewall!**
