### ISSUE TITLE
Work with existing apollo docker and carla

### ISSUE THREAD

**Issue by zillur-av** [guardstrikelab/carla_apollo_bridge#65]
I installed the carla debian in ```/opt/carla-simulator/``` and also installed apollo master branch using a docker. Do I need to install them again according to your instructions? I see you installed carla in a docker too and also used a different branch of apollo repo. My carla is working fine with the Python api and apollo waypoint demo is also working. I just need the bridge.

**Comment by zillur-av** [comment]
Thank you. I built the `apollo` according to your instructions. My local `carla simulator/server` is also working with `carla-apollo bridge` codes. However, I am unable to move the view in Carla simulator like using `WSAD`. Is that normal?

**Comment by dajiba6** [comment]
You cant move the view in carla simulator after running the bridge.py.
