### ISSUE TITLE
Failed to load default routing, error message in Dreamviewer

### ISSUE THREAD

**Issue by zillur-av** [guardstrikelab/carla_apollo_bridge#67]
I followed the instructions. Unfortunately, the car is not moving at all. Two messages are being shown on Dreamviewer console. Carla server is running and also carla-apollo bridge has been installed properly. I tried to run two python codes (bridge.py and carla_spawn_objects.py) you mentioned.

`Failed to load default routing. Please make sure the file exists at /apollo/modules/map/data/carla_town01_default_cycle_routing.txt`

`Failed to load default POI. Please make sure the file exists at /apollo/modules/map/data/carla_town01/default_end_way_point.txt`

I could not find those two txt files in the directory.

![Screenshot from 2023-03-09 21-45-16](https://user-images.githubusercontent.com/54721606/224233698-2c52ad6f-bf4a-4bf5-9afd-9a3515b64620.png)

**Comment by zillur-av** [comment]
In addition, all the buttons on ```Quick Start``` and ```Others``` are not working. I am unable to turn on ```Camera Sensor```.  Also, ```components``` are all being shows as unknown.

![Screenshot from 2023-03-13 17-54-43](https://user-images.githubusercontent.com/54721606/224864988-5f844a52-a8d1-4454-b052-9cd67f6f3da6.png)

**Comment by sweartoyou** [comment]
I have same problem, how did you solve this? I really need your help, thanks

**Comment by zillur-av** [comment]
> I have same problem, how did you solve this? I really need your help, thanks

Unfortunately, I could not solve that.

**Comment by WilliaJing** [comment]
Hi,Is there this question? You can check your steps again, do you not start Carla? in addition, you can provide your picture of Terminal,and provide your operating environment.

**Comment by Michael-Fuu** [comment]
I just met the same problems. I run in a ubuntu headless cloud server and I can't make sure if Carla works fine as there is no screen, but after run two python codes (bridge.py and carla_spawn_objects.py) I get normal logs.
gpu info as below:
<img width="557" alt="image" src="https://github.com/guardstrikelab/carla_apollo_bridge/assets/55577878/86bfe93c-3d85-4986-987d-11463b4f1773">
I guess the reason may be Volatile Uncorr ?

**Comment by Michael-Fuu** [comment]
I guess the reason is xhost not work.
when I run run_docker.sh:
<img width="906" alt="image" src="https://github.com/guardstrikelab/carla_apollo_bridge/assets/55577878/b35fef01-dfb5-4836-bcda-0f5773689b0e">

after I use the method mentioned in https://github.com/guardstrikelab/carla_apollo_bridge/issues/61(xhost local:root):
<img width="916" alt="image" src="https://github.com/guardstrikelab/carla_apollo_bridge/assets/55577878/d9aa29ad-2126-43bb-8307-546d3de7790a">
and run run_docker.sh again, still get the same result:
<img width="911" alt="image" src="https://github.com/guardstrikelab/carla_apollo_bridge/assets/55577878/42e51e3d-c018-447f-9442-3001d9b0c822">

**Comment by Michael-Fuu** [comment]
After about a week trial I finally solved the problem above and succeed to run carla apollo bridge.
In summary, mainly solve two problems.
The first problem is about the docker network and cyber ip.As I mentioned above, I found in apollo cyber environment I can not find any nodes of cyber bridge, this mean that apollo cyber nodes can not communicate with carla cyber nodes.I solved this by put three dockers(apollo\bridge\carla) in the same bridge network with different ip, not host as default.
The second problem is about the x11 stream between carla simulator and carla bridge. After I solved the first problem I just  synchronize the cyber RT envrionment, I still can not see any apollo cyber nodes(only carla_spawn_objects and cyber_bridge_node, show as pic above).Before I run bridge container and carla container, remember export DISPLAY and type: xhost local:root first.

**Comment by phamhieutn44** [comment]
> After about a week trial I finally solved the problem above and succeed to run carla apollo bridge. In summary, mainly I solved two problems. The first problem is about the docker network and cyber ip.As I mentioned above, I found in apollo cyber environment I can not find any nodes of cyber bridge, this mean that apollo cyber nodes can not communicate with carla cyber nodes.I solved this by put three dockers(apollo\bridge\carla) in the same bridge network with different ip, not host as default. The second problem is about the x11 stream between carla simulator and carla bridge. After I solved the first problem I just synchronize the cyber RT envrionment, I still can not see any apollo cyber nodes(only carla_spawn_objects and cyber_bridge_node, show as pic above).Before I run bridge container and carla container, remember export DISPLAY and type: xhost local:root first.

Hello, thank you for sharing how to solved the problem. I have the same problem with you but when I put three dockers in bridge network, I can connect carla with bridge but the apollo dreamview do nothing. Can you show how you fix the network of apollo docker? Thank you.

**Comment by Michael-Fuu** [comment]
> > After about a week trial I finally solved the problem above and succeed to run carla apollo bridge. In summary, mainly I solved two problems. The first problem is about the docker network and cyber ip.As I mentioned above, I found in apollo cyber environment I can not find any nodes of cyber bridge, this mean that apollo cyber nodes can not communicate with carla cyber nodes.I solved this by put three dockers(apollo\bridge\carla) in the same bridge network with different ip, not host as default. The second problem is about the x11 stream between carla simulator and carla bridge. After I solved the first problem I just synchronize the cyber RT envrionment, I still can not see any apollo cyber nodes(only carla_spawn_objects and cyber_bridge_node, show as pic above).Before I run bridge container and carla container, remember export DISPLAY and type: xhost local:root first.
> 
> Hello, thank you for sharing how to solved the problem. I have the same problem with you but when I put three dockers in bridge network, I can connect carla with bridge but the apollo dreamview do nothing. Can you show how you fix the network of apollo docker? Thank you.

1. use docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' + container_id to check ip if on the same bridge
2. change cyberip in cyber/setup.bash with the ip and source cyber/setup.bash,
3. finally run bootstrap, you can use cyber_node list to check again if there exists cyber nodes.

**Comment by phamhieutn44** [comment]
> > > After about a week trial I finally solved the problem above and succeed to run carla apollo bridge. In summary, mainly I solved two problems. The first problem is about the docker network and cyber ip.As I mentioned above, I found in apollo cyber environment I can not find any nodes of cyber bridge, this mean that apollo cyber nodes can not communicate with carla cyber nodes.I solved this by put three dockers(apollo\bridge\carla) in the same bridge network with different ip, not host as default. The second problem is about the x11 stream between carla simulator and carla bridge. After I solved the first problem I just synchronize the cyber RT envrionment, I still can not see any apollo cyber nodes(only carla_spawn_objects and cyber_bridge_node, show as pic above).Before I run bridge container and carla container, remember export DISPLAY and type: xhost local:root first.
> > 
> > 
> > Hello, thank you for sharing how to solved the problem. I have the same problem with you but when I put three dockers in bridge network, I can connect carla with bridge but the apollo dreamview do nothing. Can you show how you fix the network of apollo docker? Thank you.
> 
> 1. use docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' + container_id to check ip if on the same bridge
> 2. change cyberip in cyber/setup.bash with the ip and source cyber/setup.bash,
> 3. finally run bootstrap, you can use cyber_node list to check again if there exists cyber nodes.

Thank you very much. I've solved my problem.

**Comment by WilliaJing** [comment]
It looks like this issue hasn’t been active in longer than a few weeks. In the absence of more information, we will close it, If you find that this is still a problem, please feel free to reopen it.

**Comment by jakobfrosch** [comment]
> After about a week trial I finally solved the problem above and succeed to run carla apollo bridge. In summary, mainly I solved two problems. The first problem is about the docker network and cyber ip.As I mentioned above, I found in apollo cyber environment I can not find any nodes of cyber bridge, this mean that apollo cyber nodes can not communicate with carla cyber nodes.I solved this by put three dockers(apollo\bridge\carla) in the same bridge network with different ip, not host as default. The second problem is about the x11 stream between carla simulator and carla bridge. After I solved the first problem I just synchronize the cyber RT envrionment, I still can not see any apollo cyber nodes(only carla_spawn_objects and cyber_bridge_node, show as pic above).Before I run bridge container and carla container, remember export DISPLAY and type: xhost local:root first.

Thank you very much for sharing the problem and finding a solution. The problem also occurs to me. However, I'm not sure how to add the containers to the same network after already starting them.
Is the solution that you shut down the containers and then restart with docker run -d ... --network=guardstrikelab --ip 172.18.0.2 or does something have to be changed in the config files?

**Comment by Michael-Fuu** [comment]
> 

you should add the containers to the same network before you start the containers by docker run ... --network, when you close the containers and want to run it again, just use docker start is fine.Nothing need to be changed, I am not sure what problems trouble you, maybe you can tell more details about your problems.
