### ISSUE TITLE
How to run Apollo 8.0 with bridge

### ISSUE THREAD

**Issue by Kim-mins** [guardstrikelab/carla_apollo_bridge#68]
Hi! I'm trying to run Apollo on Carla as an agent via bridge, and I can successfully run Apollo **7.0** with Carla.
However, I want to run the latest version of Apollo(version 8.0), but I have some trouble during the trials.
**So I want to ask if there are any formal instructions to run latest version of Apollo on Carla with the bridge.**
For the reference, here are the descriptions on my trials.

### 1. Cloning Apollo from [main repository](https://github.com/ApolloAuto/apollo) instead of the [modified one](https://github.com/guardstrikelab/apollo).
I do know that there are some modifications on Apollo side for bridging. So I changed the code manually following the commit logs(6 commits), after cloning the main repository.
There were no errors during the installation and I followed the instruction(running DreamView and Carla simulator), but after running bridge on a terminal and `python carla_spawn_objects/carla_spawn_objects.py` on another terminal, `Segmentation fault` occurs on the terminal running the bridge.
### 2. Cloning modified repository and pull modifications for bridging by changing remote origin.
I saw [the issue here](https://github.com/guardstrikelab/carla_apollo_bridge/issues/65#issuecomment-1462065008), and I also tried to apply the modifications by changing remote origin, which means 1) cloning main repository and 2) changing remote origin to `git remote set-url origin https://github.com/guardstrikelab/carla_apollo_bridge.git` and pull) There are no errors during the installation, but after following the instructions(run DreamView, run Carla, run bridge, run spawning), I could see the spawned ego vehicle on Carla, but there are no changes on DreamView UI (which means a black screen with a message 'Please send car initial position and map data.').

**Comment by charles-lei** [comment]
Apollo v8.0 has not been tested yet. We will try to update this repo to support Apollo v8.0 in the near future. Thanks for your trials and these useful feedback.

**Comment by Kim-mins** [comment]
Thank you for the reply!

**Comment by yellinshadows** [comment]
> Apollo v8.0 has not been tested yet. We will try to update this repo to support Apollo v8.0 in the near future. Thanks for your trials and these useful feedback.

Hi, may I check if the version now support Apollo v8.0? If it does, is there any additional requirements or operations needed when setting up the bridge?
Thanks :D
