### ISSUE TITLE
Questions about shutting down the bridge and respawn the ego car

### ISSUE THREAD

**Issue by Cyrus-k** [guardstrikelab/carla_apollo_bridge#71]
Hi, developers, when I used your bridge these days, I found some problems and I would like to know whether it is a bug.
The first question is when I use keyboard interrupt ctrl+c to shut down the bridge. I cannot shut down and the log shows as follow:
![shutdown](https://user-images.githubusercontent.com/55689315/228864314-12409a29-e69d-4076-86e3-d3967b5d591b.jpg)
I found that why it cannot be shut down is due to line 387 in the picture below. Maybe the synchronous_mode has something wrong? I am not for sure about that but it stuck.
![code](https://user-images.githubusercontent.com/55689315/228866549-27a3a4be-3d39-491b-8302-36ce3b59e472.jpg)
Another question is when I use ctrl+c to stop the carla_spawn_objects.py (without shutting down the bridge), it stops right. But when I run this script again and try to send routing request to start co-simulation. Although the bridge shows it can create the ego control both in carla and Apollo, something wrong happens to the bridge.
![applycontrol](https://user-images.githubusercontent.com/55689315/228866460-95163b43-2f30-49d2-ba5a-9f0f3f623ba5.jpg)
The bridge cannot apply control to the ego vehicle in carla. I would like to know why.
Thanks for your patience.

**Comment by WilliaJing** [comment]
At present, if you have a car hit the roadside, you want restart now,I kown,you can try to follow the steps below:
* use Ctrl+C to close the carla_spawn_Objects.py
* close the terminal of bridge.py
*  docker restart carla-simulator-1 
*  python carla_cyber_bridge/bridge.py
*  python carla_spawn_objects/carla_spawn_objects.py

**Comment by WilliaJing** [comment]
It looks like this issue hasn’t been active in longer than a few weeks. In the absence of more information, we will close it, If you find that this is still a problem, please feel free to reopen it.
