### ISSUE TITLE
Error when try to build and run apollo

### ISSUE THREAD

**Issue by hugopinho0** [guardstrikelab/carla_apollo_bridge#72]
When I try to do the step **Make the GPU version:** and run the following command:
```bash
./apollo.sh build_gpu
```

 I get this error : 
```bash
(09:59:17) ERROR: /apollo/modules/perception/camera/lib/obstacle/detector/smoke/BUILD:7:13: C++ compilation of rule '//modules/perception/camera/lib/obstacle/detector/smoke:smoke_region_output_cuda' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF ... (remaining 151 argument(s) skipped)
nvcc fatal   : Unsupported gpu architecture 'compute_89'
(09:59:17) INFO: Elapsed time: 25.692s, Critical Path: 18.82s
(09:59:17) INFO: 1548 processes: 1005 internal, 543 local.
(09:59:17) FAILED: Build did NOT complete successfully

```

What changes can I do to fix it? 

The steps of installing Carla and the bridge worked correctly, I just can't do the build of Apollo to get it working. 

At the moment my system has the following cuda version.

# OS Version
Ubuntu Server 20.04.6 

# Nvcc Version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0

**Comment by mkjooriah** [comment]
It seems that you have an NVIDIA GPU with Ada Architecture which requires cuda-toolkit [version >=11.8](https://docs.nvidia.com/cuda/ada-compatibility-guide/index.html#building-applications-using-cuda-toolkit-11-8), which means that your cuda 11.1 tools will not be able to generate cubin native to the NVIDIA Ada GPU architecture (compute capability 8.9).

You can start by applying the solution mentioned in this comment https://github.com/ApolloAuto/apollo/issues/14247#issuecomment-1002855431 and adapt it to your GPU architecture as mentioned in this [NVIDIA guide](https://docs.nvidia.com/cuda/ada-compatibility-guide/index.html#building-applications-using-cuda-toolkit-11-8:~:text=compute_86%0A%20%20%2D%2Dcompile%20%2Do%20%22Release%5Cmykernel.cu.obj%22%20%22mykernel.cu%22-,Mac/Linux,-/usr/local/cuda/bin/nvcc%0A%20%20%2Dgencode%3Darch%3Dcompute_60%2Ccode). It should be enough to add the flags for to generate cubins native to the Ampere architecture (compute capability 8.0 and 8.6):
```
-gencode=arch=compute_86,code=sm_86
-gencode=arch=compute_86,code=compute_86
```

**Comment by hugopinho0** [comment]
Thanks for the suggestion, it worked perfectly  for this problem :D 

> It seems that you have an NVIDIA GPU with Ada Architecture which requires cuda-toolkit [version >=11.8](https://docs.nvidia.com/cuda/ada-compatibility-guide/index.html#building-applications-using-cuda-toolkit-11-8), which means that your cuda 11.1 tools will not be able to generate cubin native to the NVIDIA Ada GPU architecture (compute capability 8.9).
> 
> You can start by applying the solution mentioned in this comment [ApolloAuto/apollo#14247 (comment)](https://github.com/ApolloAuto/apollo/issues/14247#issuecomment-1002855431) and adapt it to your GPU architecture as mentioned in this [NVIDIA guide](https://docs.nvidia.com/cuda/ada-compatibility-guide/index.html#building-applications-using-cuda-toolkit-11-8:~:text=compute_86%0A%20%20%2D%2Dcompile%20%2Do%20%22Release%5Cmykernel.cu.obj%22%20%22mykernel.cu%22-,Mac/Linux,-/usr/local/cuda/bin/nvcc%0A%20%20%2Dgencode%3Darch%3Dcompute_60%2Ccode). It should be enough to add the flags to generate cubins native to the Ampere architecture (compute capability 8.0 and 8.6):
> 
> ```
> -gencode=arch=compute_86,code=sm_86
> -gencode=arch=compute_86,code=compute_86
> ```
