### ISSUE TITLE
Error when starting the route

### ISSUE THREAD

**Issue by hugopinho0** [guardstrikelab/carla_apollo_bridge#74]
Hello again, 

After I get Apollo working, when I follow all the steps in the documentation to run the example. 

I get this error and can't get the car to follow the defined route. Has anyone had this problem or have any suggestions on how I can solve this problem? 

> E0403 22:18:33.270490  6624 channel_manager.cc:326] [spawn_objects] newly added writer(belongs to node[conti_radar_front])'s message type[apollo.drivers.ContiRadar] does not match the exsited writer(belongs to node[cyber_bridge_node])'s message type[apollo.drivers.PointCloud]. 

![gnome-shell-screenshot-OY2Y21](https://user-images.githubusercontent.com/30537147/229640877-0e2046a9-6be9-465e-820a-25e6b13cade7.png)

Best Regards

**Comment by zhangs666** [comment]
do you fix this?

**Comment by SEEKERXC** [comment]
Hello! We have fixed this issue in the latest version and will soon release it

**Comment by SEEKERXC** [comment]
Problem solved by [Release 0.3.0](https://github.com/guardstrikelab/carla_apollo_bridge/releases/tag/0.3.0), so this issue is closed.
