### ISSUE TITLE
How to reload the map of Carla_town02 in Dreamview？

### ISSUE THREAD

**Issue by LCaptainJackSparrow** [guardstrikelab/carla_apollo_bridge#75]
I followed the steps below, but the operation failed；

1. Using RoadRunner: Imported Carla_town02.xodr map and exported base_map.bin,base_map.txt and base_map.xml;
2. Place the above files in /apollo/modules/map/data/carla_town02
3. Generated routing_map.txt,routing_map.bin,sim_map.bin and sim_map.txt, using the bazel-bin/modules/map/tools/sim_map_generator, bash scripts/generate_routing_topo_graph.sh
4. Place the above files in /apollo/modules/map/data/carla_town02
5.  ./apollo.sh build_gpu
6.  I have tried restarting dreamview and adding file paths to **global_flagfile.txt**, but it still doesn't work
![2023-04-04 15-50-13屏幕截图](https://user-images.githubusercontent.com/101320438/229724801-c436e381-6462-4d88-8960-f1a1ea0f58ae.png)

**Comment by fpeanut** [comment]
你好 请问拟解决这个问题了嘛

**Comment by SEEKERXC** [comment]
Hello. Let me explain this issue to you:
The coordinates of the map converted by roadrunner are transformed through UTM projection, and the coordinates of the plane coordinate values are very large. Generally, the x coordinate increases by 166021 and the y coordinate increases by 10000000.0.
We obtain the coordinates of various objects in the Carla world in Bridge and send them to Apollo. We only take negative values for y and do not perform corresponding coordinate transformations, so the operation will fail.
It is worth mentioning that we have already converted more Carla maps and are running normally. We will soon add them to this project.

**Comment by LCaptainJackSparrow** [comment]
Thank you very much for your reply. Let me understand the reason for this problem.

**Comment by SEEKERXC** [comment]
Problem solved by [Release 0.3.0](https://github.com/guardstrikelab/carla_apollo_bridge/releases/tag/0.3.0), so this issue is closed.
