### ISSUE TITLE
libGL error: No matching fbConfigs or visuals found

### ISSUE THREAD

**Issue by looles** [guardstrikelab/carla_apollo_bridge#77]
![图片](https://user-images.githubusercontent.com/44311409/230397688-1059df80-0701-4f50-94f6-795c8f24bdd4.png)
When I run manual control.py in docker, I will encounter the problem in the picture above. Is there anyone who can help me?SOS！！！

**Comment by meua** [comment]
You can try doing this:
1: Run the carla-server container with the following flags:
```bash
docker run -it  --name=carla-server --privileged  -v /tmp/.X11-unix:/tmp/.X11-unix:rw -v /usr/lib/nvidia:/usr/lib/nvidia --device /dev/dri --rm -e __NV_PRIME_RENDER_OFFLOAD=1 -e __GLX_VENDOR_LIBRARY_NAME=nvidia -e DISPLAY=$DISPLAY  -e NVIDIA_VISIBLE_DEVICES=all -e NVIDIA_DRIVER_CAPABILITIES=all --gpus=all --name=carla-server --net=host -d carlasim/carla:0.9.13
```
instead the tutorial command (DO NOT USE the COMMAND below)
```bash
docker run --gpus=all --name=carla-server --net=host -d carlasim/carla:0.9.13
```
In addition, the second step is needed:

2: Modify The Dockerfile inside carla_apollo_bridge/docker folder and Add these Environment Variables in the bottom of the file:
```bash
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES all
ENV SDL_VIDEO_GL_DRIVER = libGL.so.1.7.0  #libGL.so.1
ENV DISPLAY=$DISPLAY
ENV LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/lib/nvidia"
ENV  __NV_PRIME_RENDER_OFFLOAD=1
ENV __GLX_VENDOR_LIBRARY_NAME=nvidia
```
I guess just the first 2 ENV are enough, however, I guess the addition of other ones brought more stability to open the pygame simulator. In addition a third step could be added, however it can crash a virtual machine (happened with me). It is removing the xorg.conf file inside /etc/X11 folder.

**Comment by WilliaJing** [comment]
It looks like this issue hasn’t been active in longer than a few weeks. In the absence of more information, we will close it, If you find that this is still a problem, please feel free to reopen it.
