### ISSUE TITLE
ERROR: ld.so: object 'libcaffe2_gpu.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

### ISSUE THREAD

**Issue by NavyHub** [guardstrikelab/carla_apollo_bridge#82]
## Describe the bug

> ERROR: ld.so: object 'libcaffe2_gpu.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

## Steps to Reproduce the Problem

1. execute the command `cd carla_apollo_bridge/docker && ./build_docker.sh && ./run_docker.sh`
1. enter cyber container : `docker exec -ti carla_cyber_0.9.13 bash` 

## Screenshots or Video

![image](https://user-images.githubusercontent.com/40234106/233079499-f1bfbe7e-a39f-494e-87ff-06b6748ba18b.png)

## Environments (please complete the following information):
 - System info: `Linux jia 5.15.0-69-generic #76~20.04.1-Ubuntu SMP Mon Mar 20 15:54:19 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
 - Cuda version: `NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0  `
 - Docker version: `Docker version 20.10.17, build 100c701`
 - Docker-compose version: `Docker Compose version v2.0.1`

**Comment by JasonBourne1998** [comment]
Hi @NavyHub , Have you solved this issue? I meet this problem too.

**Comment by meua** [comment]
I also encountered this problem, but it does not seem to affect the normal operation, let's troubleshoot this problem together.
```bash
root@f0a9ff4d588e:/apollo# ./apollo.sh build_cyber opt
ERROR: ld.so: object 'libcaffe2_gpu.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libcaffe2_gpu.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libcaffe2_gpu.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libcaffe2_gpu.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libcaffe2_gpu.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libcaffe2_gpu.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libcaffe2_gpu.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
System check passed. Build continue ...
ERROR: ld.so: object 'libcaffe2_gpu.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libcaffe2_gpu.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libcaffe2_gpu.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libcaffe2_gpu.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
[WARNING] ESD CAN library supplied by ESD Electronics does not exist. If you need ESD CAN, please refer to third_party/can_card_library/esd_can/README.md.
ERROR: ld.so: object 'libcaffe2_gpu.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Running build under CPU mode. No GPU is required to run the build.
[INFO] Start building, please wait ...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling --host_jvm_args=-XX:-UseParallelGC
Extracting Bazel installation...
.......
____Downloading file:/home/tmp/v1.14.2.tar.gz: 9,158,656 bytes
____Loading package: cyber/examples
[INFO] Building on x86_64...
[INFO] Building with --jobs=12 --ram_utilization_factor 80 for x86_64
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling --host_jvm_args=-XX:-UseParallelGC
INFO: (05-10 02:52:32.147) Found 547 targets...
Slow read: a 35277032-byte read from /root/.cache/bazel/_bazel_root/540135163923dd7d5820f3ee4b306b32/external/fastrtps/lib/libfastrtps.so.1.5.0 took 5115ms.
INFO: (05-10 02:54:47.015) Elapsed time: 136.972s, Critical Path: 34.37s
[INFO] Skipping revision recording
============================
[ OK ] Build passed!
[INFO] Took 882 seconds
============================
```

**Comment by meua** [comment]
> Hi @NavyHub , Have you solved this issue? I meet this problem too.

The same problem can be found here:https://github.com/ApolloAuto/apollo/issues/8833

You can modify the /apollo/apollo_base.sh file and comment out the following configuration line of code
```bash
  export LD_PRELOAD="$PRELOAD"
```

**Comment by newwj** [comment]
> Hi @NavyHub , Have you solved this issue? I meet this problem too.

 @JasonBourne1998 We have fixed this error, you can pull the code, delete the carla_cyber_0.9.13 image of this machine, and build.

**Comment by WilliaJing** [comment]
It looks like this issue hasn’t been active in longer than a few weeks. In the absence of more information, we will close it, If you find that this is still a problem, please feel free to reopen it.
