### ISSUE TITLE
carlasim/carla:0.9.13 keep restarting and fail in runing carla_apollo_bridge

### ISSUE THREAD

**Issue by 2019211753** [guardstrikelab/carla_apollo_bridge#83]
the instruction before **Runing carla_apollo_bridge** works well,
but after i perform these
```bash
cd /apollo/cyber/carla_bridge
python carla_cyber_bridge/bridge.py
````
error as follows:
```bash
[2023-04-24 12:27:33,509] [carla_bridge] [ERROR]: Error: time-out of 30000ms while waiting for the simulator, make sure the simulator is ready and connected to 172.17.0.1:2000
^CTraceback (most recent call last):
  File "carla_cyber_bridge/bridge.py", line 485, in <module>
    main()
  File "carla_cyber_bridge/bridge.py", line 471, in main
    carla_world = carla_client.get_world()
RuntimeError: time-out of 30000ms while waiting for the simulator, make sure the simulator is ready and connected to 172.17.0.1:2000

```

**Comment by newwj** [comment]
* Check whether Carla-Simulator-1 is running
*  Use Docker Inspect Carla-Simulator-to see the namemode name of CARLA-SIMULATOR-1 container.
If you have any questions, you can provide screenshots

**Comment by WilliaJing** [comment]
It looks like this issue hasn’t been active in longer than a few weeks. In the absence of more information, we will close it, If you find that this is still a problem, please feel free to reopen it.

**Comment by 2019211753** [comment]
> It looks like this issue hasn’t been active in longer than a few weeks. In the absence of more information, we will close it, If you find that this is still a problem, please feel free to reopen it.

sorry for ignore the message. I still have this question. Some screenshots are shown below.
![image](https://github.com/guardstrikelab/carla_apollo_bridge/assets/65377379/449015f7-05e6-495b-bb45-601a198437dd)

![image](https://github.com/guardstrikelab/carla_apollo_bridge/assets/65377379/398425a7-53f1-4036-b27c-1c0faf7e7548)

![image](https://github.com/guardstrikelab/carla_apollo_bridge/assets/65377379/7f1bde01-4475-4e98-922d-434a5b181b30)
![image](https://github.com/guardstrikelab/carla_apollo_bridge/assets/65377379/b6e5884a-3452-4d1b-acf4-6c82acff0716)

I don't know why it can't works. it seems that i follow the instructions step by step TAT. And after I performed the './docker_run_carla.sh' , it didn't evoke the UE enviroment.

Thanks a lot for your reply!

**Comment by 2019211753** [comment]
any reliable solution？TAT

**Comment by WilliaJing** [comment]
Hi,Judging from your screenshot, you have started Carla, but you did not enter Carla_cyber_0.9.14 container and execute
```
 ./apollo.sh build_cyber opt

**Comment by 2019211753** [comment]
> Hi,Judging from your screenshot, you have started Carla, but you did not enter Carla_cyber_0.9.14 container and execute
> 
> ```
>  ./apollo.sh build_cyber opt
> ```

I follow the instruction again. But after i execuate 
![image](https://github.com/guardstrikelab/carla_apollo_bridge/assets/65377379/a8f69d56-7823-4691-90da-11fda1349f56)
I'm sure that I execute the instruction sentence by sentence, including  ./apollo.sh build_cyber opt.
My carla container looks like not starting. After executing `docker ps -a`:
![image](https://github.com/guardstrikelab/carla_apollo_bridge/assets/65377379/a84d7932-f834-47b1-a873-0df39ae6fa6a)
docker logs carla-simulator-1:
![image](https://github.com/guardstrikelab/carla_apollo_bridge/assets/65377379/91ce2e31-49ba-4577-b455-ce8ddd836935)
There is nothing but sh: 1: xdg-user-dir: not found. And it seems not a error

**Comment by 2019211753** [comment]
> Hi,Judging from your screenshot, you have started Carla, but you did not enter Carla_cyber_0.9.14 container and execute
> 
> ```
> 
>  ./apollo.sh build_cyber opt

can you reopen this issue？thanks

**Comment by WilliaJing** [comment]
@2019211753 
* Check whether Carla-Simulator-1 is running

If it is running,you can try to follow the steps below
1. Install firewall (if already installed, skip this step)
```
sudo apt-get install firewalld
```
2. close firewall
```
systemctl stop firewalld.service
```
3. Test whether the container carla_cyber_0.9.14 can connect to the Carla service
```
docker exec -ti carla_cyber_0.9.14 bash
curl -v 172.17.0.1:2000
```
If the following information is displayed,the firewalld was closed
>root@a5b2fce9f53f:/apollo# curl -v 172.17.0.1:2000
 Rebuilt URL to: 172.17.0.1:2000/
Trying 172.17.0.1...
TCP_NODELAY set
 Connected to 172.17.0.1 (172.17.0.1) port 2000 (#0)
 GET / HTTP/1.1
 Host: 172.17.0.1:2000
 User-Agent: curl/7.58.0
 Accept: */*

Else the following content is displayed, it indicates that the firewall has not been successfully shut down and Carla cannot perform joint simulation with Apollo normally:
>curl: (7) Failed to connect to 172.17.0.1 port 2000: No route to host

**You first need to turn off the firewall!**

**Comment by 2019211753** [comment]
After execuate  curl -v 172.17.0.1:2000
```bash
* Rebuilt URL to: 172.17.0.1:2000/
*   Trying 172.17.0.1...
* TCP_NODELAY set
* connect to 172.17.0.1 port 2000 failed: Connection refused
* Failed to connect to 172.17.0.1 port 2000: Connection refused
* Closing connection 0
curl: (7) Failed to connect to 172.17.0.1 port 2000: Connection refused
```
It seems that there is no progress running in the port.?
I used to deploy based on "https://github.com/AuroAi/carla_apollo_bridge"，the bridge and the carla simulator works well, except that there is no carla graphic interface.

**Comment by WilliaJing** [comment]
Did you Install firewall and close firewall?

**Comment by 2019211753** [comment]
I tried to download carla0.9.14 in my server instead of running in docker，it works.
