### ISSUE TITLE
bridge是否可以重置车辆位置

### ISSUE THREAD

**Issue by WilliaJing** [guardstrikelab/carla_apollo_bridge#87]
当一次模拟结束的时候，当我不关闭bridge，仅仅是ctrl+c关掉carla_spawn_objects来关掉自己的ego_vehicle时，当我再次重新启动carla_spawn_object，bridge会报如下错误，但是apollo和carla中都是能正常显示ego_vehicle的，但是apollo无法在send routing request之后按照路径行驶车辆。与此同时，我想使用set_initial_pose来重置车辆位置时，似乎是因为模拟carla-ros-bridge的不完全，无法使用这个脚本来重置位置，所以请问bridge能否重置自己车辆位置。（目前我的方式是重启bridge以及carla_spawn_object来重新进行模拟）

**Comment by newwj** [comment]
![image](https://user-images.githubusercontent.com/50048416/235125756-867dddc8-5448-4c73-bd6a-3811f10ed8d8.png)

**Comment by zhangs666** [comment]
请问这个问题解决了吗

**Comment by WilliaJing** [comment]
Hi,I use restart to reset the location of the car,you can try to follow the steps below:
* use Ctrl+C to close the carla_spawn_Objects.py
* close the terminal of bridge.py
* docker restart carla-simulator-1
* python carla_cyber_bridge/bridge.py
* python carla_spawn_objects/carla_spawn_objects.py

**Comment by zhangs666** [comment]
好的好的
