### ISSUE TITLE
wsl2 apollo8.0 carla编译问题

### ISSUE THREAD

**Issue by fpeanut** [guardstrikelab/carla_apollo_bridge#91]
你好，请问wsl2上编译carla apollo时总是编译不通过，是什么原因。
![image](https://user-images.githubusercontent.com/58199989/237053429-e2ce4c88-b2eb-4f6d-b783-f461dbd6d041.png)

**Comment by charles-lei** [comment]
Hi, please try to use Ubuntu instead. That hasn't been tested on Windows.

**Comment by fpeanut** [comment]
> Hi, please try to use Ubuntu instead. That hasn't been tested on Windows.
好的谢谢
