### ISSUE TITLE
关于apollo8.0 carla联合仿真

### ISSUE THREAD

**Issue by fpeanut** [guardstrikelab/carla_apollo_bridge#93]
你好请问，目前最新版本carla 支持在apollo8.0的编译吗

**Comment by newwj** [comment]
Hi,Apollo v8.0 has not been tested yet. We will try to update this repo to support Apollo v8.0 in the near future. Thanks for your trials and these useful feedback.

**Comment by fpeanut** [comment]
好的谢谢，我们想尝试自己更新下carla apllo8.0的编译，现在更新了cyber的基础镜像源，还有src内proto的文件，请问还有哪些需要更新？

**Comment by newwj** [comment]
We haven't learned about Apollo8.0 yet, and this is still planned. If you succeed, you can pull request to us!

**Comment by fpeanut** [comment]
好的，我们现在是打算将src内的文件复制到apollo8.0 cyber内，然后直接在apollo8.0容器内编译搭桥，这样是否可行

**Comment by Michael-Fuu** [comment]
> 好的，我们现在是打算将src内的文件复制到apollo8.0 cyber内，然后直接在apollo8.0容器内编译搭桥，这样是否可行

Hi,我们有类似的计划，你们成功了吗？能请教一下咋做吗？直接将source内的文件复制过去还要注意什么？是不是可以不用carla-apollo容器，只用一个apollo容器和carla容器就行了
