### ISSUE TITLE
有关apollo8 与carla联合仿真的一些修改测试和问题

### ISSUE THREAD

**Issue by fpeanut** [guardstrikelab/carla_apollo_bridge#96]
## In what area(s)?

> /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release
## Describe the proposal

你好，作者，请问有没有时间搞一下apollo8.0与carla的联合仿真，我最近将src内的源码放到apollo8 cyber里修改了一些代码编译通过，能够连接到apollo，从https://github.com/Flycars/apollo_map处下载了地图放到apollo8内，但是在运行carlaspawnobjects.py是发现carla自车的位置和dreamview内自车位置不一样，而且dreview内不能看到地图，只有点了simctrol才能看到；还有dreamview打开camera右下角图片显示不出来，但是由这个channel的

**Comment by WilliaJing** [comment]
Hi，Recently, we will be upgrading to Apollo8.0.

**Comment by fpeanut** [comment]
好的 谢谢
