### ISSUE TITLE
carla_spawn_objects.py中断后再次运行报错

### ISSUE THREAD

**Issue by zhangs666** [guardstrikelab/carla_apollo_bridge#97]
![image](https://github.com/guardstrikelab/carla_apollo_bridge/assets/87601573/59a14d82-836e-42b0-8077-6fc14119a611)

E0518 10:16:42.794441 12779 node_manager.cc:101] [spawn_objects] this process will be terminated due to duplicated node[carla_spawn_objects], please ensure that each node has a unique name.

**Comment by WilliaJing** [comment]
Under normal circumstances, you need to enter CTRL+C on the keyboard, and you need to close the terminal about bridge.py.
In addition, I can’t see your picture.

**Comment by zhangs666** [comment]
当我重启整个环境，问题就解决了
