### ISSUE TITLE
whether Apollo5.0 is availiable or not?

### ISSUE THREAD

**Issue by 2019211753** [guardstrikelab/carla_apollo_bridge#98]
I see 'it was tested with Carla 0.9.14 and the Apollo newer than v7.0.0', does it mean that Apollo5.0 is availiable? thanks!

**Comment by WilliaJing** [comment]
Hi,We started to use Apollo7.0, and plan to adapt the latest 8.0 version. If you need 5.0, you can test it yourself, thank you.

**Comment by 2019211753** [comment]
thanks for your reply
