### ISSUE TITLE
Running Bridge on a headless cloud server

### ISSUE THREAD

**Issue by Michael-Fuu** [guardstrikelab/carla_apollo_bridge#99]
## Running bridge without a display on screen only access by dreamview

I have tried to run carla simulator on a headless cloud server(no screen) but failed, due to the cloud server can not start x server.
as I use startx, it returns:
<img width="889" alt="image" src="https://github.com/guardstrikelab/carla_apollo_bridge/assets/55577878/e7622baf-7669-46c5-b640-2fad305fae90">
and I tried Xvfb to simulate a fake screen, also failed.

then I changed to use RenderOffScreen mode to start a Carla simulator, it works, and I ran car-apollo-bridge docker and type 
commands as your docs shows.
<img width="1063" alt="image" src="https://github.com/guardstrikelab/carla_apollo_bridge/assets/55577878/6a9ebd6c-ae58-4f3d-b6f4-8f3aff5ceeed">
everything seems work fine but I can't connect Carla simulator with Dreamview, and logs show the veihcle does move any where.
<img width="265" alt="image" src="https://github.com/guardstrikelab/carla_apollo_bridge/assets/55577878/0db7e95a-95c6-4d0f-98e8-568b8ad6cad5">
gpu usage:
<img width="557" alt="image" src="https://github.com/guardstrikelab/carla_apollo_bridge/assets/55577878/d4797367-c5c1-4cf0-914e-3b59bc63fae3">

It would be great to show some advice about how to bridge on a headless cloud server since I just want to use Dreamview and don't need a display of Carla environment?

**Comment by fpeanut** [comment]
你可以在window上运行carla，让后修改carla_cyber_bridge/config内的yaml文件的ip地址，跟你的windowIP地址对上即可
